import { recallPrompts } from './recall-prompts.mjs';
// Editorial material and practice briefs. These are fictional teaching scenarios.
export const openings = {
  'UX-001': 'The screen says “Request received.” Maya puts her phone away, then picks it up again. Does she have an appointment, or has she only joined a queue?\n\nAlex initially studies the confirmation screen. But Maya’s uncertainty started days earlier, when her referral disappeared between two services. Following that whole attempt changes what he thinks he is designing.',
  'UX-002': 'Alex brings two booking screens to a review. Both look calm and carefully arranged. Then Maya tries to change an appointment. On one screen, she can check the new time before committing. On the other, the old appointment vanishes before she knows whether the new one is available.\n\nThe room had been debating which screen looked better. Now it has a more useful question: can Maya finish this task with confidence and recover if she makes a mistake?',
  'UX-003': 'Maya reaches the end of the booking flow. Confetti fills the screen. Underneath it, a message says the clinic will confirm her request later. She closes the celebration and calls reception.\n\nAlex has made the screen cheerful, but Maya still cannot plan her day. To improve this experience, he needs to decide what confidence would actually require.',
  'UX-004': 'At his desk, Alex completes the booking flow without a pause. Later, Maya tries it on the way home. The train enters a tunnel, her connection drops, and she cannot tell whether the request went through.\n\nThe interface is identical. The conditions are not. Alex’s next design decision begins with those conditions.',
  'UX-005': 'CarePath tells Maya her referral has been sent. The clinic says it has not arrived. Each team checks its own system and finds nothing wrong. Maya is the only person following the entire journey.\n\nAlex follows her calls. He discovers that the experience depends on a handoff no screen designer has been asked to own.',
  'UX-006': 'The team shares a promising result: more people are finishing the new booking flow. Alex is ready to celebrate until reception reports a rise in calls from people who thought a request was a confirmed appointment.\n\nThe numbers are measuring a real improvement in one place and missing a new problem in another. Alex needs a way to judge both before recommending the change.',
  'UX-007': 'Maya opens CarePath to choose an appointment. A banner says the clinic needs more information, but the calendar fills most of the screen. She taps a date.\n\nIn the review, someone points to the banner: “But we told her.” Alex watches the recording again. Maya followed the strongest invitation the page gave her. The message existed; it never became part of her decision.',
  'UX-008': 'Alex moves every important detail onto the appointment page. The clinic, date, preparation note, and change request are all present. Maya still pauses: which details describe her current appointment, and which describe the change she is considering?\n\nAdding the right information has not given it a readable structure. Alex starts again with what belongs together.',
  'UX-009': 'Maya is checking the clinic address before confirming a transfer. A feedback prompt covers the page. She dismisses it, returns to the form, and has to work out where she left off.\n\nThe prompt took only a moment. Recovering the decision took longer. Alex begins to count the interruptions the product adds to a task that already demands care.',
  'UX-010': 'Maya returns to a shortlist of clinics. She recognises their names but cannot remember which one offered the access support she needs. She opens each detail page again.\n\nAlex adds the relevant access information to each shortlist item. Now Maya can compare the evidence where she makes the choice. The interface has taken back some work it had left to memory.',
  'UX-011': 'The first clinic in Maya’s results is already selected. It has the earliest appointment, but reaching it would mean a difficult journey. Maya nearly continues without opening the alternatives.\n\nAlex asks how that default was chosen. A small presentation decision has given one value, speed, more influence than the person’s other needs.',
  'UX-012': 'Maya taps to submit an appointment change. The connection drops before a confirmation appears. She is tempted to tap again. Has the first request failed, or would another tap send it twice?\n\nAlex draws the uncertain state before drawing the success screen. Recovery starts by being honest about what the system knows.',
};

Object.assign(openings, {
  'UX-013': '“Can we add a calendar button?” The request reaches Alex as a small interface change. He follows it back to Maya, who is trying to keep an appointment while arranging work and transport. A button may help, but first he needs to understand the work it is meant to support.',
  'UX-014': 'Maya sees that her referral has been sent and assumes the clinic will contact her. The clinic is waiting for her to choose a slot. Nothing moves. Alex discovers that two people can read the same status and predict entirely different next steps.',
  'UX-015': 'Alex asks the team what an appointment request becomes after acceptance. One screen calls it a booking, another calls it a referral, and support uses a third term. Before drawing another screen, he needs a world whose objects and rules stay consistent.',
  'UX-016': 'The team describes CarePath as a queue. Maya expects that waiting will eventually bring her to the front. But some referrals need more information before they can move at all. Alex follows the useful promise of the metaphor and the false expectation it creates.',
  'UX-017': 'Alex watches Maya book a visit. The form takes a few minutes. Checking the referral, calling a family member, arranging transport, and deciding whether the time works take much longer. His screen flow has left out most of the task.',
  'UX-018': 'Maya phones reception after booking. Someone adds “build a dashboard” to the backlog. Alex holds the observation apart from the proposed answer: she might need clearer confirmation, a missing preparation detail, or help with a change. Each explanation would produce a different requirement.',
  'UX-019': 'CarePath’s team asks Alex to arrange interviews about booking. He asks what they will decide afterward. Simplifying the form, improving clinic information, and repairing availability would require different evidence. The research plan begins when the decision becomes clear.',
  'UX-020': '“Let patients request another clinic,” someone suggests. It sounds straightforward until Alex asks whether clinics are interchangeable, whether the data is current, and who will handle a rejected transfer. One feature request turns out to contain several separate bets.',
  'UX-021': 'The team has survey responses saying clinic comparison would be useful. Alex still cannot tell whether people understand the options or whether a clinic can receive a transfer reliably. He separates the questions before choosing the next method.',
  'UX-022': 'The first volunteers know CarePath’s terminology and have reliable phones. Their sessions run smoothly. Alex looks at the recruitment list and realises that people who needed help, abandoned the journey, or could not use it never had a chance to appear.',
  'UX-023': 'Maya agrees to discuss a booking experience. During the interview, a question edges toward private health information. Alex has to decide whether that detail is necessary, whether Maya expected to share it, and how she can decline without pressure. Research quality includes the conditions under which evidence is obtained.',
  'UX-024': 'One participant misunderstands a status. The team wants to call it a universal problem and approve a redesign. Alex keeps the observation, the explanation, and the proposed fix separate. Each deserves attention; each needs different support.',
  'UX-025': 'The research report is finished, but CarePath keeps changing. A clinic alters its process and patients develop a workaround the team has never seen. Alex needs a way for new evidence to reach decisions while those decisions can still change.',
  'UX-026': 'The team ships clinic comparison on schedule. More people request a transfer, yet Maya still cannot reach an appropriate appointment. Alex follows the chain between the feature delivered and the progress it was meant to create.',
  'UX-027': '“Would you use clinic comparison?” produces an encouraging answer. “Tell me about the last time your appointment did not work for you” opens a different conversation. Alex hears about transport, work, uncertainty, and a phone call that solved what the app could not.',
  'UX-028': 'The backlog says “improve booking,” followed by a list of features. Alex rewrites the problem around moments when people cannot make progress. Suddenly, the same obstacle has several possible solutions, and one proposed feature has no clear need beneath it.',
  'UX-029': 'The team debates the comparison screen’s layout. Alex returns to an earlier uncertainty: can the clinics actually accept the transfers being offered? He chooses a small service test because a polished screen cannot answer that question.',
  'UX-030': 'Alex recommends a change and hears, “What makes us sure?” His notes contain the answer, but the team cannot follow the path from observation to choice. He opens that path for inspection, including the evidence that made the decision uncomfortable.',
  'UX-031': 'Several patients describe booking as “confusing.” Alex lays out the episodes behind the word. One person could not interpret a status; another understood it but could not act. Giving both notes the same label would hide the difference that matters for design.',
  'UX-032': 'Maya calls after submitting a request. Alex can record the call, but its cause is still uncertain. Was confirmation unclear, did something change, or did she need information the flow never offered? An insight has to earn the step beyond observation.',
  'UX-033': 'The persona sheet gives Maya a favourite drink and a photograph. Neither helps Alex choose what a returned-referral screen should do. He replaces decoration with the circumstances, strategies, and evidence that could change the design.',
  'UX-034': 'The user story says Maya changes an appointment. Alex writes the episode around it: she is at work, a family member has offered transport, and she cannot risk losing the old slot before the new one is secure. The missing conditions change the interaction.',
  'UX-035': 'Maya experiences a single delay. Alex traces it through a referral, a clinic inbox, a staff decision, and a missing notification. A journey map shows what the wait feels like; a blueprint helps explain how the service produces it.',
  'UX-036': 'Alex has enough material for a long presentation. The team has enough time for one decision. He follows a patient episode, shows the wider pattern and its limits, then asks for a specific change. The story works only if the evidence survives the telling.',
  'UX-037': 'Maya knows the kind of help she needs but cannot tell which directory category contains it. The information exists. Alex studies how it is organised and how a person is expected to find a path through it.',
  'UX-038': 'A clinic label makes immediate sense to staff and very little sense to Maya. Alex asks what she expects to find behind it. Her answer changes the naming discussion from which phrase sounds professional to which phrase makes the right promise.',
  'UX-039': 'Maya opens a link directly to a clinic page. After checking the details, she wants to compare another option without losing her place. Alex designs for that arrival, not only the journey that begins on the home page.',
  'UX-040': 'Maya searches using the words she would say to reception. The results use different language, and every title sounds equally broad. Alex looks at what each result reveals before asking her to open it.',
  'UX-041': 'The button says “Submit.” Maya hesitates because she cannot tell whether it sends a request or confirms an appointment. Alex changes the words only after checking what the system will actually do. The label is part of the interaction contract.',
  'UX-042': 'The request fails and Maya reads “Something went wrong.” She still needs to know whether anything was sent and whether trying again is safe. Alex starts the rewrite with those questions rather than a friendlier apology.',
  'UX-043': 'A coordinator needs to work through many referrals; Maya needs to understand one appointment choice. Alex considers whether each activity calls for a command, a comparison, direct manipulation, or a conversation. The interaction style follows the work.',
  'UX-044': 'Maya hovers over a label and discovers it is clickable. Later, a prominent control opens something different from what she expected. Alex reviews the invitation and consequence of each action before adjusting its appearance.',
  'UX-045': 'CarePath asks Maya for information she already supplied. Some fields protect a necessary decision; others remain because an old form asked for them. Alex traces each question to a purpose and removes the work no longer needed.',
  'UX-046': 'Maya submits a change. The button becomes disabled and the page goes quiet. Alex separates acknowledging the tap, describing the processing state, and confirming the actual outcome. A disabled control cannot carry all three messages.',
  'UX-047': 'The page gives the appointment, a promotion, and a critical status the same visual weight. Maya has to decide where to look before she can decide what to do. Alex builds the hierarchy around the decision she came to make.',
  'UX-048': 'Alex fits the desktop booking form onto a phone. Maya can technically use it, but comparing options now means moving between screens and remembering details. He revisits the task, the content order, and the conditions of use along with the width.',
  'UX-049': 'Two CarePath teams have built different date pickers and repaired different accessibility problems. A third team is about to start again. Alex asks which decisions should be shared, who should maintain them, and how teams will know they can rely on them.',
  'UX-050': 'The component sheet shows a beautiful button. Alex asks what it says while waiting, how it receives keyboard focus, and what happens after failure. A shared component becomes useful when its behaviour is as explicit as its appearance.',
  'UX-051': 'One team writes “Done,” another writes “Success,” and a third writes “Request received.” The underlying event is the same, but the promises are different. Alex brings content rules into the system so people can recognise a state across the service.',
  'UX-052': 'The system proposal covers every CarePath screen. The team cannot yet show where it saves effort or improves quality. Alex chooses a contained pilot with enough real variation to expose what the system must handle.',
  'UX-053': 'A team changes a shared component to solve an urgent local problem. Another team discovers the change after release. Alex follows the decision path that was missing: contribution, review, exceptions, ownership, and communication.',
  'UX-054': 'The system has more installations than last month. Patients still encounter conflicting status messages. Alex puts adoption beside the quality and effort it was meant to improve, then asks whether the system is changing either.',
  'UX-055': 'Maya finishes the digital steps, but the clinic cannot deliver the appointment she expected. Alex follows the promise beyond the app into policy, staff work, data, and capacity. The boundary of the product is smaller than the boundary of her experience.',
  'UX-056': 'Maya needs to change an appointment but cannot discover which service handles the request. The help content explains the process only after she finds the right page. Alex treats finding and understanding the service as part of receiving it.',
  'UX-057': '“Your appointment is confirmed” is a short sentence resting on several commitments. Alex traces the slot, staff, records, reminders, and authority to change it. The frontstage message is reliable only while those backstage conditions hold.',
  'UX-058': 'The journey map shows Maya waiting. It does not yet show who has her request, which system holds its state, or who should contact her. Alex adds those connections to discover where the service needs a new responsibility.',
  'UX-059': 'The workshop map looks orderly until a receptionist explains the workaround used every morning. It protects patients from a gap the formal process does not acknowledge. Alex makes room for the people doing the work to change the design.',
  'UX-060': 'The booking prototype works in a session. Then the team rehearses it with clinic staff, a delayed response, and an unavailable slot. The promise begins to strain. Alex uses that rehearsal to find what the service must be able to do before launch.',
});

export const modules = {
  M01: { title: 'Define what better means', story: 'Maya can complete a booking form and still struggle to get care. Alex starts by following the whole attempt, then asks what a better outcome would look like.', challenge: 'The booking team wants to remove the review step to increase completion. Reception thinks more patients will mistake a request for a confirmed appointment. Prepare a one-page recommendation.', deliver: ['Describe Maya’s goal and the evidence that would show she reached it.', 'Trace the interface, service handoff, and real-world outcome.', 'Compare keeping, changing, and removing the review step.', 'Choose one usability measure, one experience measure, and a condition that would change your recommendation.'], review: ['A completed form is distinguished from a confirmed appointment.', 'The proposal considers context, recovery, and the work passed to reception.', 'The recommendation names an uncertainty and a way to investigate it.'], twist: 'Reception cannot take extra calls during the pilot. Reconsider the recovery route before recommending a release.' },
  M02: { title: 'Make the next action clear', story: 'The referral is waiting for information, but Maya keeps trying to book. Alex examines what the page asks her to notice, remember, and do.', challenge: 'Design CarePath’s returned-referral state for Maya, who is travelling, distracted, and unsure what information is missing.', deliver: ['Sketch the state and its most important action.', 'Explain the grouping, wording, non-colour cues, and information kept visible.', 'Show what survives interruption and a lost connection.', 'Plan a test of noticing, understanding, action, and recovery.'], review: ['The interface directs attention to the actual next step.', 'Important meaning survives colour loss and interruption.', 'The test observes behaviour instead of asking whether the screen looks clear.'], twist: 'The referral status changes while Maya is away. Show how she finds out on return without losing her work.' },
  M03: { title: 'Follow the work behind the tap', story: 'A referral, an appointment request, and a confirmed appointment sound similar until Maya needs to change one. Alex makes the objects and rules explicit.', challenge: 'Model what happens when Maya cannot find a suitable appointment and asks to move to another clinic.', deliver: ['Separate the goal, tasks, and interface actions.', 'Draw the objects, states, actors, and handoffs.', 'Write one scenario, one user story, and two testable requirements.', 'Identify a mismatch between what Maya believes and how the service works.'], review: ['Referral and appointment states remain distinct.', 'The model includes an exception and a recovery route.', 'Each requirement traces back to evidence or an explicit assumption.'], twist: 'The receiving clinic accepts the referral but has no available slots. Update the model and the promise shown to Maya.' },
  M04: { title: 'Investigate before choosing', story: 'The team proposes clinic comparison. Alex needs to know why people fail to find care before treating comparison as the answer.', challenge: 'Prepare a research plan for deciding whether CarePath should offer alternative clinics when no suitable slot is available.', deliver: ['Name the decision, owner, deadline, and competing explanations.', 'Match each question to a method and its limits.', 'Define a sample that includes people missing from product analytics.', 'Describe consent, data handling, analysis, and a result that would change the decision.'], review: ['Methods answer distinct questions rather than repeat preferences.', 'The sample reflects conditions that might change the finding.', 'The plan can still influence the decision before commitment.'], twist: 'You have half the time you expected. Narrow the claim and explain what the remaining evidence cannot establish.' },
  M05: { title: 'Turn learning into a habit', story: 'One study gives Alex a direction. Keeping that direction useful means returning to people, assumptions, and decisions as the product changes.', challenge: 'Design four weeks of discovery for the alternative-clinic feature, linked to a live opportunity map.', deliver: ['Connect an outcome to opportunities, solutions, and assumptions.', 'Choose the riskiest assumption and the smallest credible test.', 'Give product, design, engineering, research, and operations concrete roles.', 'Show how weekly evidence changes the map and the next commitment.'], review: ['The outcome describes progress for people.', 'Customer contact changes a decision rather than filling a calendar.', 'A failed assumption has a defined consequence for the plan.'], twist: 'Interviews suggest strong demand, but clinics cannot reliably maintain availability. Decide what to learn or repair next.' },
  M06: { title: 'Build an argument from evidence', story: 'Maya’s story is memorable. Alex must find out which parts describe a wider pattern and which belong to her particular situation.', challenge: 'Use a small set of authorised research notes to explain one CarePath breakdown. If using invented notes, label them clearly.', deliver: ['Separate observations, interpretations, patterns, and implications.', 'Trace a theme to supporting evidence and a contradicting case.', 'Choose a persona, scenario, journey, or blueprint only if it changes a decision.', 'Present the finding to a designer and an operational owner with the same confidence boundary.'], review: ['A vivid quote does not stand in for prevalence.', 'Contradicting evidence remains visible.', 'The proposed action follows from the finding without pretending certainty.'], twist: 'A newly observed case contradicts your strongest theme. Revise the explanation before revising the slide.' },
  M07: { title: 'Give the service a readable structure', story: 'Maya searches using everyday language; the directory uses organisational labels. Alex follows where that mismatch blocks the journey.', challenge: 'Design the information structure for finding and comparing an appropriate CarePath clinic.', deliver: ['Define content types, relationships, metadata, and ownership.', 'Propose labels and synonyms using the person’s vocabulary.', 'Show browse, search, filtered results, and a useful no-results state.', 'Describe how you will test findability and keep the structure current.'], review: ['Labels predict what the destination contains.', 'Search recovery supports the goal without inventing availability.', 'The model gives changing information an owner and update rule.'], twist: 'Two clinics merge, but patients still search for both old names. Preserve findability and explain the changed relationship.' },
  M08: { title: 'Write the next useful sentence', story: '“Request received” leaves Maya guessing. Alex treats wording as part of the service’s behaviour and checks what people believe after reading it.', challenge: 'Write CarePath messages for submitted, awaiting review, missing information, confirmed, and failed appointment requests.', deliver: ['For each state, state what happened, who acts next, and when.', 'Adapt one message for screen, email, and assisted support.', 'Include a stressful exception and an accessible alternative.', 'Plan a comprehension check and name who maintains the wording.'], review: ['The words never imply confirmation before it exists.', 'Tone fits the consequence and the person’s situation.', 'The same state means the same thing across channels.'], twist: 'The clinic cannot promise a response time. Rewrite the message with useful uncertainty and a credible help route.' },
  M09: { title: 'Design the whole interaction', story: 'Maya compares, selects, submits, waits, and sometimes changes her mind. Alex designs the transitions between those moments.', challenge: 'Prototype an appointment change from the current booking through confirmation, including one failed submission.', deliver: ['Explain the controls, defaults, validation, and review step.', 'Show immediate feedback and the authoritative final state.', 'Preserve progress across devices, interruption, and retry.', 'Include keyboard operation and a safe route out of the change.'], review: ['The original appointment is handled explicitly.', 'Retries cannot silently produce duplicate requests.', 'The interface makes the consequence of each action predictable.'], twist: 'Two family members act on the same appointment at once. Add identity, conflict feedback, and a recovery rule.' },
  M10: { title: 'Make good decisions reusable', story: 'Different CarePath teams keep inventing different versions of “pending.” Alex turns the shared meaning into a system teams can maintain.', challenge: 'Create a small status-and-action component family and a plan for piloting it with two CarePath teams.', deliver: ['Separate semantic tokens, component behaviour, content, and implementation.', 'Document normal, loading, error, disabled, and focus states.', 'Set a contribution, exception, versioning, and migration process.', 'Measure useful adoption and accessibility quality.'], review: ['Status meaning is consistent across design and code.', 'Exceptions have a reason, owner, and review point.', 'Adoption measures whether the system helps teams and users.'], twist: 'A required accessibility repair changes a widely used component. Plan the release and identify who must migrate.' },
  M11: { title: 'Make the promise operational', story: 'The app can promise a call, but somebody has to make it. Alex brings policy, capacity, staff work, and recovery into the design.', challenge: 'Blueprint CarePath’s no-suitable-slot journey across digital self-service and assisted support.', deliver: ['Connect frontstage touchpoints to staff, systems, policy, and capacity.', 'Name the owner, information, and time limit for each handoff.', 'Prototype a support interaction as well as the interface.', 'Measure patient outcomes and staff burden together.'], review: ['Every promise has a credible backstage capability.', 'Recovery works when the preferred channel fails.', 'A channel shift does not masquerade as a resolved need.'], twist: 'Demand doubles for one week. Show which promises change and how people are supported during the backlog.' },
  M12: { title: 'Use a prototype to learn', story: 'Alex has several plausible designs and limited time. The prototype has to expose the uncertainty that could change the choice.', challenge: 'Evaluate two approaches to CarePath’s clinic comparison before committing to one.', deliver: ['Write the uncertainty and choose a suitable prototype fidelity.', 'Specify participants, tasks, observation, and method limitations.', 'Separate observation, interpretation, severity, and confidence.', 'Revise one design and explain what must be tested again.'], review: ['The prototype makes the risky behaviour testable.', 'Tasks avoid revealing the intended solution.', 'Recommendations are proportionate to consequence and evidence.'], twist: 'Participants complete the task but misunderstand the appointment status. Decide whether the test supports release.' },
  M13: { title: 'Ask what the number means', story: 'More transfer requests look encouraging until Alex follows what happens afterward. Measurement has to reach the outcome.', challenge: 'Design an experiment and measurement plan for CarePath’s alternative-clinic feature.', deliver: ['Draw the causal chain from exposure to receiving care.', 'Define outcome, diagnostic, and guardrail measures with denominators and windows.', 'Specify assignment, exposure, meaningful effect, and data-quality checks.', 'Predefine how conflicting results change the rollout decision.'], review: ['Assignment and exposure are not confused.', 'The plan separates causal evidence from correlation.', 'The decision considers unequal outcomes and operational burden.'], twist: 'Requests rise, completed appointments stay flat, and support contacts increase. Write the decision and the next investigation.' },
  M14: { title: 'Find who the design leaves out', story: 'The usual path works for some patients. Alex follows the paths that fail and asks who can change the rules behind them.', challenge: 'Audit CarePath’s booking and document-upload journey for exclusion, consent, and recoverable harm.', deliver: ['Map demands against varied capabilities and circumstances.', 'Test keyboard, reading order, zoom, errors, and an alternate channel.', 'Review each data request for purpose, choice, and downstream use.', 'Assign repair, escalation, monitoring, and remedy responsibilities.'], review: ['Accessibility is evaluated across the complete task.', 'An alternative route preserves outcome and dignity.', 'Affected people have influence and a usable route to correction.'], twist: 'The assisted route is accessible but misses the application deadline. Fix the service rule, not only the interface.' },
  M15: { title: 'Decide what AI may do', story: 'A recommendation can sound certain while its clinic data is stale. Alex designs the evidence, authority, and recovery around the model.', challenge: 'Evaluate a proposed AI assistant that explains clinic options and recommends the next booking action.', deliver: ['Compare the AI proposal with a credible non-AI baseline.', 'Define permitted actions, human authority, uncertainty, and abstention.', 'Storyboard a correct result, confident error, stale source, and failed handoff.', 'Specify evaluation, monitoring, override, pause, and remedy.'], review: ['The assistant cannot turn missing evidence into a confident claim.', 'Human review has time, information, authority, and capacity.', 'Evaluation covers the joint service and its consequences.'], twist: 'Acceptance rises while staff stop checking recommendations. Explain how you would distinguish better performance from automation bias.' },
  M16: { title: 'Carry the decision into delivery', story: 'The team agrees that clinic data needs repair. Alex now has to connect the evidence to ownership, scope, rollout, and lasting value.', challenge: 'Present a decision brief for a small clinic-verification pilot, then turn it into a release plan.', deliver: ['Compare opportunities and state the bet, principle, and overturning assumption.', 'Define decision rights and connect discovery to delivery.', 'Choose a small ethical test with outcome and stop conditions.', 'Plan staged release, response, rollback, maintenance, and review.'], review: ['The brief makes trade-offs and counterevidence visible.', 'The pilot preserves the mechanism needed to learn.', 'Named owners can pause and repair the service after launch.'], twist: 'Leadership asks to expand before the outcome window closes. Give a defensible recommendation and an evidence threshold.' },
  M17: { title: 'Defend the complete design', story: 'Alex has built a chain of decisions. The final case tests whether that chain holds when someone asks where its weakest claim comes from.', challenge: 'Choose a consumer, enterprise, service, or high-stakes problem. Build a ten-minute case that connects evidence to one consequential design decision.', deliver: ['Show the problem frame, competing explanations, and research plan.', 'Model the objects, states, handoffs, and responsible owners.', 'Present alternatives, evaluation, value, harm, and remaining uncertainty.', 'Define rollout, monitoring, recovery, and what would change your recommendation.'], review: ['Every major claim has traceable support and a stated limit.', 'The system includes edge conditions and affected non-users.', 'The case explains why the choice is defensible and when it should change.'], twist: 'A reviewer identifies a group missing from your research. Revise the claim and next step before defending the design.' },
};

export function splitSections(md) {
  return md.split(/(?=^## )/m).filter(part => /^## /.test(part)).map(part => {
    const newline = part.indexOf('\n');
    return { title: part.slice(3, newline).trim(), body: part.slice(newline + 1).trim() };
  });
}

const labels = { 'Core explanation': 'What this moment reveals', 'Core model': 'Why it happens', 'The essential idea': 'Why it happens', 'See the mechanism': 'Follow the mechanism', 'In a real product': 'Try another situation', 'Senior lens': 'The harder decision', 'Going deeper': 'Look more closely', 'How to use it': 'Put it to work', 'Failure modes': 'Where this can go wrong' };

export function readingModel(md, id, title) {
  const sections = splitSections(md);
  const take = pattern => sections.filter(s => pattern.test(s.title));
  const opening = openings[id] || take(/^Anchor case$/i)[0]?.body || '';
  const practice = take(/^Studio exercise$/i).map(s => s.body).join('\n\n');
  const observe = take(/^Train your UX eye$/i).map(s => s.body).join('\n\n');
  const thread = take(/^Course thread$/i).map(s => s.body).join('\n\n');
  const refs = take(/^References$/i).map(s => s.body).join('\n\n');
  const excluded = /^(Anchor case|Studio exercise|Train your UX eye|Course thread|References)$/i;
  const narrative = sections.filter(s => !excluded.test(s.title)).map(s => ({...s, label: labels[s.title] || s.title.replace(/^Illustration\s*[-:–]\s*/i, 'Worked example: ')}));
  // Keep authored order: moving explanations can break references to previous passages.
  const mechanism = narrative.find(s => /mechanism|essential idea|core (model|explanation)/i.test(s.title)) || narrative[0];
  const application = narrative.find(s => /^CarePath/i.test(s.title)) || mechanism;
  return { opening, sections: narrative, thread, refs, practice, observe,
    recall: recallPrompts[id],
    guidance: [mechanism, application].filter((s, i, arr) => s && arr.findIndex(x => x.title === s.title) === i).map(s => ({title:s.label,body:s.body})),
  };
}
