// Three additional, distinct concept checks per lesson. Each compares two claims.
// Topic ~ supported claim (including its reason) ~ competing misconception.
const rows=`
001|the unit of UX analysis~An attempt includes the goal and consequences beyond one screen.~The screen is the complete unit whenever the task is digital.|a successful submission~It can coexist with a failed experience if the service never delivers.~It establishes success if the interface displays confirmation.|improving an experience~Operational changes may be needed when the breakdown is outside the interface.~An interface change is sufficient when the complaint arrives through the app.
002|usability criteria~They must specify people, goals, and context to make the judgement meaningful.~They should stay context-free so products can be ranked on one scale.|expert efficiency~A dense interface can support expert tasks when its structure fits the work.~A dense interface is less usable regardless of the task.|learnability and efficiency~A design can perform well on one and poorly on the other.~Once a product is easy to learn, efficient expert use follows.
003|experience goals~They concern qualities such as confidence and reassurance, not only task speed.~They are another name for completion and error rates.|a satisfaction score~It needs context because the same score can reflect different experiences.~It identifies which interaction caused the feeling.|a faster booking~It needs checking for understanding because speed can hide uncertainty.~It necessarily improves confidence by reducing time spent.
004|situational constraints~Noise, movement, and privacy can change what actions are practical.~They matter only for people with a permanent impairment.|context research~Observation in relevant conditions can expose failures a desk test misses.~A controlled desk test can establish usability in every environment.|adapting the flow~Preserving progress can help interruptions without simplifying the underlying task.~A smaller layout addresses interruption as long as controls remain visible.
005|handoff ownership~A named receiver and acknowledgement make a transfer accountable.~A sent timestamp removes the need for a receiving owner.|service boundaries~A patient’s experience can cross organisations even if the product team does not.~Responsibility for UX ends at the product’s technical boundary.|tracing a referral~Following the record through states can reveal where its promise breaks.~Interviewing the front-end team is enough to verify receipt.
006|quality trade-offs~A gain in one dimension can conceal a cost in another.~Improving completion establishes an overall quality improvement.|recovery measures~They reveal whether failures leave people with a workable next step.~They are unnecessary once the main path has a high success rate.|senior judgement~It should examine effects across the journey and affected groups.~It should prioritise the metric owned by the design team.
007|attention~Task expectations influence what people notice, even when information is visible.~All sufficiently large elements receive equal attention.|comprehension~A person may notice a message without understanding its consequence.~Noticing a message establishes that its meaning is clear.|testing a warning~Observe whether it changes the relevant action, not only whether it is recalled.~A participant remembering its colour shows the warning worked.
008|proximity~Nearby elements tend to be interpreted as related.~Equal visual style always overrides physical proximity.|visual grouping~It should match semantic relationships because layout communicates structure.~It can be decorative if all labels are individually correct.|a separated action~Distance may make its relationship to nearby content less apparent.~Relationship is unaffected as long as the action has an icon.
009|resumption cost~Reconstructing the task can take longer than the interruption itself.~Only the time spent away contributes to the cost.|saved work~It preserves effort but may still need orientation on return.~It removes every need to explain where the person left off.|an interruption test~Include an actual break and observe recovery of context.~Ask whether the screen looks easy to resume without interrupting anyone.
010|recognition~Visible relevant cues can reduce the need to retrieve details from memory.~Recognition requires displaying all available information simultaneously.|comparison~Keeping selected options together supports judging differences.~Separating options into sequential screens reduces memory demands.|progressive disclosure~It can reduce clutter if decision-critical information remains available.~It improves usability whenever it hides more content.
011|default effects~A preselection influences what people accept even when it is editable.~An editable preselection has no meaningful effect on choice.|defensible defaults~They need an appropriate rationale and a clear route to change them.~They are justified whenever they improve the business metric.|informed choice~Consequences should be understandable before the person commits.~A later cancellation route is a substitute for understanding the choice.
012|uncertain submission~The action may have completed even if the response never arrived.~A network error proves the server rejected the request.|safe retries~They should prevent duplicate effects while resolving the real state.~They should create a new request each time to maximise reliability.|recovery language~It should distinguish unknown from failed or completed.~It should choose a definite outcome to keep the message reassuring.
013|goals~They describe intended progress and can survive a change of interface.~They are the sequence of controls used in the current product.|tasks~Several task strategies may serve the same goal.~Each goal has only one correct task sequence.|actions~They are concrete steps within a task, not the underlying need.~Counting actions directly measures how well the goal was met.
014|mental models~They are people’s expectations and may differ from implementation.~They are the authoritative technical model of the system.|discovering expectations~Ask people to predict what will happen, then compare with actual behaviour.~Ask whether the interface is clear and infer its mental model.|repairing mismatches~Expose the distinction that changes the person’s next decision.~Display all internal complexity so the person can learn the implementation.
015|system objects~A referral and an appointment can require different states and permissions.~Similar-looking records should share one state model.|conceptual consistency~Similar actions should produce predictable relationships between states.~Consistency means using the same layout regardless of behaviour.|model validation~Test whether people can explain and predict the system.~Approve the model when every screen has been drawn.
016|metaphor limits~A queue metaphor can mislead when priority overrides arrival order.~A familiar metaphor remains accurate even when ordering rules differ.|metaphor selection~Choose based on the expectations it supports and where they break.~Choose the most visually engaging metaphor first.|exceptions~Explain them when the metaphor would otherwise predict the wrong outcome.~Hide them to preserve the simplicity of the metaphor.
017|task analysis~It includes decisions and dependencies, not only interface steps.~It is complete when each screen has a next button.|exception paths~They can reveal requirements absent from the normal sequence.~They can be excluded if most people follow the normal path.|division of work~Staff and patient actions may depend on one another.~The patient’s task can be modelled independently of every staff action.
018|interpreting a call~It could signal uncertainty or a service failure, requiring investigation.~It directly proves the need for a status dashboard.|requirements~They should connect to an evidenced need or explicit assumption.~They become validated when written in a standard template.|solution alternatives~Different causes can require different interventions.~The same observed behaviour always calls for the same feature.
019|decision timing~Evidence must arrive while the decision can still change.~Evidence collected after commitment has the same decision value.|research ownership~A decision owner helps connect findings to action.~A research report makes decision ownership unnecessary.|negative findings~Plan what result would change the preferred direction.~Only results supporting the proposal need a response plan.
020|assumption risk~Importance and uncertainty together help prioritise testing.~The least expensive assumption is always the best first test.|operational assumptions~Clinic capacity can invalidate a desirable feature.~User demand validates the operational feasibility of a feature.|evidence strength~An assumption remains provisional until relevant evidence tests it.~Team consensus converts an assumption into a fact.
021|interviews~They can explain experiences but do not automatically establish prevalence.~Repeated interview comments estimate the population rate directly.|experiments~A valid design can estimate a treatment effect within its scope.~Any before-and-after comparison establishes causality.|surveys~Their claims depend on measurement and sample quality.~A large response count compensates for biased questions.
022|sampling dimensions~Choose differences likely to change the finding.~Choose demographics solely to make the sample appear varied.|successful users~They omit some people who could not access or complete the service.~They adequately represent people excluded by the service.|qualitative sampling~It supports depth and variation without automatically estimating prevalence.~A diverse qualitative sample establishes population percentages.
023|voluntary participation~People need a genuine ability to refuse without undue consequence.~A signed form makes pressure to participate acceptable.|data minimisation~Collect only what the research purpose needs.~Store all potentially useful data because it may help later.|withdrawal~Explain its practical limits before participation.~Promise removal from every future artefact regardless of feasibility.
024|an observation~It records what happened before assigning a cause.~It should include the researcher’s preferred causal interpretation as fact.|triangulation~Different evidence can test an explanation’s plausibility.~Repeating the same unsupported claim in several slides strengthens it.|confidence~It should match the quality and limits of evidence.~It should match the importance of persuading the audience.
025|discovery cadence~Regular contact is useful when it changes current decisions.~The number of interviews is the primary proof of learning.|existing evidence~Reviewing it may be more useful than commissioning a new study.~New research is always more valuable than earlier findings.|continuous learning~It should revisit assumptions as conditions change.~An approved roadmap removes the need to revisit assumptions.
026|outputs~Shipping comparison is an output, not proof of access to care.~Shipping is the user outcome when delivery met its deadline.|causal chains~Availability and acceptance can break the path from clicks to care.~An increase in clicks guarantees the final outcome.|outcome measurement~Follow what happens after the feature interaction.~Stop measurement at the last screen controlled by the team.
027|episode interviews~Concrete events provide actions and constraints to probe.~General preferences provide the same contextual detail.|leading questions~Mentioning the desired answer can shape the account.~Leading questions are harmless when the participant agrees readily.|future intention~It is evidence of stated intention, not guaranteed behaviour.~A confident prediction can replace observing use.
028|opportunities~They describe unmet needs or obstacles rather than features.~They are feature names phrased as benefits.|alternative solutions~Several interventions can address one opportunity.~Each opportunity should have only the team’s preferred solution.|outcomes~They describe meaningful change that the intervention aims to produce.~They are the deliverables listed in the release plan.
029|a falsifiable test~Its result can show the assumption does not hold.~It is designed primarily to collect favourable reactions.|prototype scope~It should represent the behaviour necessary to test the assumption.~Higher visual fidelity automatically produces stronger evidence.|test interpretation~A failed solution test may leave the underlying need intact.~A failed test proves that the user need does not exist.
030|decision records~They preserve why the choice made sense with the evidence then available.~They should make the final choice look inevitable.|revisit conditions~They identify evidence or changes that warrant reconsideration.~They weaken commitment and should be omitted.|alternatives~Recording them prevents later teams from losing the trade-off context.~Rejected alternatives have no future value.
031|theme development~An explanatory connection matters more than matching vocabulary.~Shared keywords establish a coherent theme.|negative cases~They can refine or challenge the pattern.~They should be removed if they reduce the theme’s clarity.|context~It helps define where the pattern applies.~It is unnecessary once enough quotes repeat a point.
032|inference~The move from behaviour to explanation should be explicit.~A plausible explanation is itself an observation.|counterevidence~Seek cases that could undermine the interpretation.~Avoid contradictory cases until the recommendation is approved.|actionability~An insight should inform a choice without pretending certainty.~An insight is actionable only when it names a feature.
033|persona detail~Include a constraint when it changes the design decision.~More biographical detail always makes a persona more useful.|evidence~Personas should reflect researched patterns rather than invented stereotypes.~A believable narrative is sufficient validation.|persona use~It should help compare choices for relevant situations.~Its main value is decorating the project presentation.
034|scenario context~Time pressure or interruption can change requirements.~The same task always has the same requirements in every situation.|scenario scope~Include consequences and what happens when the intended path fails.~End the scenario at the final click.|scenario validation~Compare it with evidence about actual activity.~Treat narrative plausibility as evidence of frequency.
035|journey maps~They foreground the person’s experience over time.~They automatically specify all system dependencies.|blueprints~They connect touchpoints to the service work supporting them.~They are primarily a way to decorate emotion curves.|waiting~Its cause may lie in backstage capacity or ownership.~The waiting screen necessarily contains the cause of delay.
036|story boundaries~State what the example illustrates and what it cannot establish.~Omit limitations when they interrupt the story.|audience relevance~Connect the finding to a decision the audience can make.~Change the evidence strength to suit the audience.|traceability~Keep the link from story to underlying evidence.~A powerful story makes supporting evidence unnecessary.
037|content availability~Content can exist yet remain practically undiscoverable.~Publishing accurate content makes it findable.|organisation~It should support how the audience seeks information.~The organisation chart is the natural structure for every audience.|findability testing~Observe whether people reach the right information.~Ask whether the navigation looks organised.
038|label prediction~The label should help someone anticipate its destination.~A label succeeds if it is internally precise.|audience vocabulary~Research terms people use before standardising labels.~Internal terms are preferable because staff already know them.|label evaluation~Test interpretation and finding behaviour in context.~Select the label with the shortest character count.
039|deep-link arrival~Orientation should work without visiting the home page first.~The home page is a prerequisite for understanding every destination.|related paths~They help people recover when the entry page is not the right match.~They should be removed to keep the entry page isolated.|location cues~They communicate position and relationships within the structure.~They are purely decorative navigation elements.
040|result snippets~They help judge relevance before opening the destination.~They should repeat the site slogan for brand consistency.|relevant attributes~Show the information needed to compare likely matches.~Hide all attributes to maximise click-through.|search success~Evaluate finding a useful answer, not clicks alone.~More result clicks always indicate better search.
041|action labels~They communicate consequence as well as what to press.~Their wording does not affect the interaction model.|status truth~Request and confirmation must remain distinct if the service treats them differently.~They can be interchangeable to simplify the copy.|copy testing~Check what action and outcome people predict.~Ask only whether the wording sounds friendly.
042|preserved work~Tell people what remains so they can recover safely.~Require re-entry after every error to avoid ambiguity.|unknown state~Do not label it failed when completion may have occurred.~A definite failure message is better than admitting uncertainty.|next action~It should be available and capable of addressing the problem.~Any help link is sufficient recovery guidance.
043|commands~They can support efficient expert work when learnable and discoverable.~They are unsuitable whenever a graphical interface exists.|conversation~It can introduce ambiguity for tasks requiring precise comparison.~It always makes complex decisions easier.|direct manipulation~Its visible objects and feedback need to match the actual model.~It works through animation regardless of semantic fit.
044|feedforward~It helps people predict the consequence before acting.~It is feedback shown after the action.|state feedback~It should show whether the action was accepted and what followed.~A pressed appearance proves completion.|discoverability~A control must be recognisable as actionable in its context.~An interactive element is discoverable because its code supports clicks.
045|field purpose~A question needs a defensible service use.~Potential future usefulness is enough reason to collect it.|timing~Ask when the person understands why the information is needed.~Ask everything at the start to avoid later steps.|optional fields~They still create effort and privacy considerations.~Making a field optional removes its design cost.
046|acknowledgement~It confirms receipt, not necessarily final completion.~It is equivalent to a completed transaction.|processing feedback~It should explain waiting and safe next actions where possible.~A disabled control alone is sufficient.|completion~It should reflect authoritative state and provide durable confirmation where needed.~An optimistic animation establishes the final state.
047|hierarchy~Relative emphasis guides the person’s next decision.~Equal emphasis avoids influencing attention.|secondary detail~It may remain accessible without competing with the primary task.~It must be deleted whenever it is not primary.|visual review~Evaluate whether important information is noticed and understood.~Evaluate only balance and aesthetic preference.
048|mobile continuity~The task may continue across interruptions and devices.~Each screen size can be treated as an unrelated journey.|comparison on mobile~Relevant differences still need to be available together or recoverably.~Reducing width justifies removing comparison information.|input conditions~Touch, movement, and one-handed use affect interaction demands.~Equivalent pixel dimensions create equivalent effort.
049|system governance~Ownership and change processes keep shared design coherent.~A component download establishes governance.|system semantics~Teams need common meanings as well as common appearance.~Matching colours makes differing states consistent.|maintenance~The system must evolve with product needs and evidence.~The first published library is a finished deliverable.
050|focus states~They make keyboard location perceivable.~They are unnecessary when the default component is clear.|error states~They need a useful recovery behaviour, not only error styling.~A red border is a complete error contract.|component completeness~Interactions and states must be specified beyond the default view.~A complete set of static sizes covers the behaviour.
051|shared wording~It should reflect shared state definitions.~It is an optional layer unrelated to system consistency.|confirmation~It must not promise more than the service has completed.~Reassurance justifies simplifying pending to confirmed.|content ownership~Someone must maintain wording when behaviour changes.~Component engineers can assume content remains valid indefinitely.
052|pilot selection~Choose real variation that can reveal limitations.~Choose only the easiest adoption case.|pilot evidence~Observe usefulness, implementation friction, and quality.~Count participants attending the launch meeting.|migration~Use pilot learning to inform subsequent adoption.~Require universal adoption before revising the system.
053|contribution~Teams need a route to propose and test shared improvements.~Only the original authors should influence the system.|exceptions~Document a rationale, owner, and review condition.~Every exception should silently become a permanent fork.|change communication~Affected teams need compatibility and migration information.~Publishing a new version is sufficient communication by itself.
054|installation counts~They indicate availability or adoption, not necessarily useful application.~They directly measure user-facing quality.|quality measures~Check relevant outcomes such as defects and accessible behaviour.~Count components in the catalogue as the quality score.|paired measures~Assess team usefulness alongside product effects.~Choose whichever metric currently looks most favourable.
055|service promises~They depend on capacity and rules as well as interfaces.~They can be assessed independently of operations.|ownership~A failure needs a responsible actor and a workable response.~A shared mailbox establishes complete accountability.|service research~Follow work across channels to find dependencies.~Restrict research to sessions inside the app.
056|access to a service~Finding and understanding it are part of the experience.~Experience begins only after sign-in.|invisible exclusion~People may fail before they generate product events.~Product analytics includes everyone who needed the service.|service language~It should connect the person’s need to the right service.~It should mirror the internal catalogue exactly.
057|frontstage~It is the visible interaction supported by less visible work.~It can make promises independently of backstage readiness.|backstage~Data and staff commitments determine whether the promise holds.~Backstage problems can always be solved through clearer wording.|reliable confirmation~Verify the conditions that make the statement true.~Optimise the feeling of certainty before checking the state.
058|blueprint handoffs~Specify responsibility, information, and timing.~Draw arrows without assigning ownership.|failure points~They reveal where the service needs support or redesign.~They are evidence that the person needs better training.|blueprint use~It should inform operational decisions and coordination.~Its quality is established by visual completeness alone.
059|staff workarounds~They may compensate for a gap in the formal service.~They are necessarily careless deviations.|co-creation~Participants need scope to alter the proposed model.~Participation means approving a prepared solution.|facilitation~Make different perspectives and power visible.~Treat silence as agreement across all roles.
060|service rehearsal~Include realistic delays, handoffs, and staff decisions.~Treat every backstage action as instant success.|prototype scope~Make the dependency under investigation realistic.~Visual detail is the only meaningful fidelity dimension.|rehearsal findings~They can expose a promise the organisation cannot yet fulfil.~They establish production capacity from a single successful enactment.
061|prototype purpose~Start with the uncertainty that could change the decision.~Start with the preferred prototyping tool.|fidelity~Choose realism in the dimensions relevant to the question.~High fidelity is always more informative.|prototype limits~Document what the simulation cannot establish.~A successful simulation proves the live system will work.
062|divergence~Explore meaningful alternatives before narrowing prematurely.~Produce cosmetic variations of one predetermined solution.|validation layers~Need evidence and solution evidence answer different questions.~Evidence of a need approves the first implementation.|convergence~Use explicit criteria and evidence to choose.~Choose solely on the polish of the presentation.
063|task wording~It should express a goal without revealing the intended route.~It should name the exact control to click.|moderator assistance~It can mask problems and must be considered in interpretation.~Assisted completion counts as unqualified success.|understanding~Check what participants believe happened after acting.~Correct clicks are sufficient evidence of correct belief.
064|expert inspection~It identifies plausible issues using specialist judgement.~It measures actual issue prevalence in the user population.|walkthroughs~They can examine whether task steps are understandable.~They replace all observation of real people.|combined evidence~Inspection and user research can answer complementary questions.~The methods should produce identical evidence to be useful.
065|finding consequence~Explain the effect on the task and person.~Report the interface location as the entire finding.|confidence~Distinguish observed evidence from extrapolation.~Use the same certainty for every recommendation.|action prioritisation~Consider harm and dependencies as well as frequency.~The most repeated complaint is always the first fix.
066|iteration scope~Choose changes that make the next uncertainty testable.~Change everything to maximise the chance of improvement.|comparison~Preserve enough context to interpret the new result.~Any later result can be attributed to the redesign.|retesting~Changed behaviour may require renewed evaluation.~A previous successful test permanently validates the flow.
067|event meaning~A booking event needs a precise state definition.~Its name alone establishes a universal meaning.|actor and context~They help distinguish superficially similar events.~They are unnecessary metadata once an event is counted.|outcome interpretation~Follow downstream states to know what the event achieved.~The final logged click is the final user outcome.
068|overall criteria~They should represent meaningful value rather than a convenient event.~They should be whichever measure moves fastest.|guardrails~Some harms should block release despite a positive primary result.~Every harm can be averaged away by a large enough gain.|decision rules~Specify how metrics affect the choice before reading results.~Choose the most persuasive metric after analysis.
069|diagnostics~They help explain behaviour without necessarily defining success.~Every diagnostic increase is a positive outcome.|data-quality checks~They test whether the measurement can be trusted.~They establish that the feature benefits people.|primary metrics~They should connect to the intended outcome.~They should include all recorded events equally.
070|causal scope~A test estimates effects for its design and exposed population.~Randomisation guarantees universal applicability.|treatment definition~The intervention and comparison must be explicit.~The feature name is enough to define the treatment.|mechanisms~An effect alone does not establish why it occurred.~A significant effect proves the proposed psychological explanation.
071|assignment validity~Broken allocation can undermine the comparison.~A small p-value compensates for allocation errors.|measurement consistency~Groups need comparable outcome definitions.~Different logging is harmless if each group has many events.|analysis timing~Unplanned repeated peeking can distort inference.~Stopping at the first favourable result preserves the planned error rate.
072|invalid tests~Keep the cause and limits visible for future learning.~Archive only the favourable numbers.|learning records~Include changes needed to prevent recurrence.~Exclude implementation issues because they are not design insights.|reporting~Distinguish operational learning from unsupported causal claims.~Treat an invalid positive result as weak proof of success.
073|capability~It can vary by situation and over time.~It is a fixed binary property of a user.|inclusive scope~Consider resources, environment, and support as well as impairment.~Consider only users with diagnosed disabilities.|design response~Reduce mismatched demands and provide alternatives.~Ask people to adapt to the average user profile.
074|task demands~Analyse sensory, cognitive, motor, and practical requirements.~Assess only visual complexity.|mismatch~It arises between demands and available capability or resources.~It is solely a deficit in the person.|intervention~Change the demand or provide a workable alternative.~Explain the existing difficult step more forcefully.
075|focus entry~Move focus predictably when a dialog opens.~Leave focus behind the overlay.|focus return~Restore a sensible location when the dialog closes.~Return focus to the top of the document every time.|announcements~Programmatic information should communicate relevant state changes.~Visual changes are sufficient for every input and reading mode.
076|non-colour meaning~Use text or symbols and programmatic information alongside colour.~A more saturated colour solves colour-only meaning.|reading order~It should preserve the relationships needed to act.~Visual position is sufficient semantic structure.|status actions~A perceivable status still needs a clear next step where action is required.~Perceiving the status guarantees successful recovery.
077|influence~Guidance can help, but must support informed goals.~All influence is equally manipulative.|opt-out friction~A formally available escape can still impose unreasonable burden.~An opt-out link proves the choice is fair.|evaluation~Examine understanding and consequences, not conversion alone.~Higher acceptance establishes a beneficial default.
078|refusal~It needs to be meaningful within the actual service relationship.~Consent is voluntary whenever a reject button exists.|later control~People may need to review or change permissions.~The first click settles all future data uses.|accountability~Data handling must follow the stated purpose.~Consent transfers all responsibility to the participant.
079|AI fit~Compare inference with simpler ways of meeting the need.~AI is preferred whenever it can produce an output.|problem framing~Start with the human task and consequence.~Start with the model’s available features.|success~Judge useful outcomes as well as prediction quality.~Benchmark accuracy alone defines product success.
080|human oversight~It requires time, information, and authority to act.~A human name on the process guarantees control.|automation levels~Allocate authority according to consequence and capability.~More automation always means less responsible design.|intervention~People need a usable way to stop or correct consequential action.~A feedback form after harm is sufficient control.
081|calibrated trust~Reliance should match actual capability and limits.~Maximum trust is the ideal for every feature.|expectation setting~Explain what the system can and cannot do.~Use human-like confidence to simplify limitations.|uncertainty~It should help the person choose an appropriate next action.~It should be hidden to avoid damaging engagement.
082|immediate recourse~Help the affected person recover now.~Collecting a rating is enough recovery.|missing evidence~It should remain unknown rather than become a confident claim.~A plausible completion is preferable to an incomplete answer.|failure learning~Investigate the mechanism after containing the harm.~Retrying until success removes the need to investigate.
083|model evaluation~It is one layer within a wider task and service evaluation.~It can replace observing people use the feature.|human behaviour~Reliance and workarounds can change the effective outcome.~Model performance determines behaviour directly.|product value~Measure whether the task and consequences improve.~Measure only whether outputs seem fluent.
084|drift~Workflow and user behaviour can change even with stable model scores.~Only model weights can drift.|monitoring ownership~Signals need a responsible responder and action path.~Dashboards alone establish monitoring capability.|aggregates~They can hide subgroup or operational failures.~Stable average performance rules out emerging harm.
085|opportunity framing~Describe the unmet progress before selecting an intervention.~Describe the requested feature as the user problem.|prioritisation~Compare value, evidence, constraints, and alternatives.~Rank by stakeholder seniority.|counterevidence~It may justify choosing a different opportunity.~It should be deferred until after the roadmap is accepted.
086|principle usefulness~It helps choose between competing options.~It is useful if every possible option can claim to follow it.|exceptions~A boundary prevents blind application where conditions differ.~A principle should override all context.|rationale~It explains why the rule supports the intended outcome.~A memorable phrase needs no supporting reasoning.
087|delivery evidence~Implementation can reveal assumptions needing revision.~Evidence loses relevance once coding begins.|shared decisions~Teams need a route to change scope or behaviour.~Researchers only need to send findings to a channel.|learning continuity~Carry uncertainty into delivery instead of pretending it disappeared.~Treat handoff as the end of discovery.
088|counterarguments~Address strong alternatives and contrary evidence.~Omit them to keep the narrative confident.|audience adaptation~Change emphasis without changing evidential strength.~Change confidence to match the audience’s expectations.|decision focus~Clarify what choice the evidence supports.~Present all activity without naming the required decision.
089|decision rights~They clarify who resolves cross-team conflicts.~They are unnecessary when all teams act reasonably.|shared meanings~Service states need coherence across local interfaces.~Visual consistency can replace state consistency.|local optimisation~It can shift costs or break another part of the journey.~Improving every team metric guarantees a coherent service.
090|lifecycle value~Include repeated use, support, maintenance, and exit.~Launch adoption captures the lifetime value.|burden~A feature can create ongoing work after initial benefit.~A positive first session excludes future burden.|exit~Safe departure and data handling are part of the experience.~UX responsibility ends when engagement stops.
091|teardown evidence~Separate what is observed from inferred causes.~A screenshot reveals the conversion effect.|alternative explanations~Keep them visible until evidence distinguishes them.~Choose the most persuasive interpretation and present it as fact.|system context~Investigate operational and behavioural conditions behind the interface.~The visible surface is the full product experience.
092|problem boundaries~Be specific enough to investigate without fixing a solution.~A problem should cover every organisational issue.|competing frames~They can expose different causes and interventions.~They are unnecessary once a stakeholder names the feature.|evidence~It should be able to change the frame.~The frame should remain fixed to protect planning certainty.
093|assumption mapping~Connect uncertain claims to consequences if they fail.~List assumptions without considering decision impact.|method choice~Match the evidence needed for each decision.~Use the team’s favourite method for every question.|thresholds~State what result would change the choice before collecting evidence.~Decide what counts as success after the results arrive.
094|state coherence~Interface, data, and service transitions need compatible meanings.~A clear interface can fully compensate for contradictory records.|system models~Expose objects, actors, responsibilities, and exceptions.~Specify only the visible screens.|design scope~Changes may be needed beyond the product team’s current boundary.~Exclude dependencies the team does not directly own.
095|affected groups~Include people who bear consequences without using the interface.~Only active users belong in the risk analysis.|controls~They should address the specific mechanism and consequence of harm.~A general disclaimer controls any identified risk.|evaluation~Check whether the control actually works.~Documenting the control is sufficient evidence of effectiveness.
096|claim traceability~Reviewers should find the evidence behind the recommendation.~A coherent presentation removes the need to inspect sources.|uncertainty~Name the weakest claim and a way to test it.~Hide weak claims until after approval.|revisability~A defensible case explains what would change the recommendation.~A strong case is one that cannot be revised.
097|human-centred iteration~Evidence should influence framing and design choices.~Workshop completion proves human-centred practice.|participation~It must have the possibility of changing the work.~It is meaningful whenever users attend a session.|process quality~Judge the decisions and outcomes enabled by the process.~Judge compliance with a fixed sequence of artefacts.
098|non-digital alternatives~Policy or staff changes may solve the need more directly.~Digital transformation is the default best intervention.|cost boundaries~Include costs shifted to patients and staff.~Measure only the organisation’s digital transaction cost.|exclusion~A cheaper channel may still make access worse for some people.~Lower unit cost implies wider access.
099|status semantics~Text and programmatic state should preserve the meaning.~A colour key makes programmatic information unnecessary.|contrast~It matters but does not resolve colour-only distinctions.~Enough contrast solves every colour-related access issue.|redundant cues~They offer multiple ways to understand the same state.~They are wasteful repetition that should always be removed.
100|headings~They should help predict and navigate the content.~They should be intriguing even if uninformative.|consequential detail~Keep it available where decisions require it.~Remove it to improve scan speed.|reading modes~Support quick orientation and deeper examination.~Optimise only for scanning because people never read carefully.
101|intrinsic complexity~Some difficulty belongs to the decision itself.~Every difficult choice indicates poor interface design.|avoidable load~Remove demands that do not help the task.~Remove every detail that requires thought.|simplification~Make complexity manageable without concealing important trade-offs.~Make the choice feel easy by hiding its consequences.
102|state freshness~Show changes that occurred while the person was away.~Resume old state without checking for updates.|orientation~Explain where work paused and what remains.~Preserved fields make orientation unnecessary.|recovery testing~Include interruption and changed conditions.~Infer recovery quality from the uninterrupted happy path.
103|expertise~It varies by task and can change over time.~It is a permanent label assigned to each person.|expert paths~They should speed work without removing discoverable commands.~They should replace visible controls for everyone.|learning support~Offer help when relevant and keep it recoverable.~Show guidance only once during initial onboarding.
104|target spacing~It affects accidental activation as well as speed.~Only target area matters.|model boundaries~Movement-time estimates do not measure the whole experience.~A faster predicted movement proves better UX.|consequence~Protect costly actions even when a shortcut is possible.~Place every action for minimum movement regardless of risk.
105|reassurance~It should follow truthful state and available control.~Warm wording can compensate for unknown outcomes.|recovery confidence~Durable evidence helps people know what happened.~A disappearing toast is always sufficient proof.|trust repair~Demonstrate a reliable path forward after acknowledging the failure.~Avoid mentioning the failure to protect the brand.
106|wait timescale~Seconds and days require different support.~One spinner is appropriate for every delay.|time estimates~They need a basis and qualification when uncertain.~A precise estimate is better even without evidence.|leaving the page~Explain whether work continues and how the outcome will arrive.~Assume people know whether closing the page is safe.
107|exceptions~They are part of the workflow model, not merely edge annotations.~They can be excluded from requirements until launch.|handoffs~They need clear state and responsibility.~A transfer arrow establishes complete coordination.|shared understanding~Different actors may hold conflicting beliefs about the same request.~One database state guarantees everyone interprets it alike.
108|user stories~They describe intended value but may need more detail for complex behaviour.~They fully replace use cases and specifications.|scenarios~They place activity in a concrete context.~They are lists of implementation tasks.|traceability~Requirements should connect back to the evidence and activity.~A consistent document format establishes validity.
109|constraint conflicts~Resolve them explicitly rather than optimising one requirement in isolation.~User-facing requirements automatically override every constraint.|quality requirements~They describe properties such as reliability and access.~They are optional refinements after feature delivery.|data requirements~They can determine whether the interface promise is possible.~They do not affect UX until the database is implemented.
110|heuristics~They support judgement but are not proof of usability.~Passing a heuristic checklist establishes every user outcome.|patterns~They carry assumptions that need contextual checking.~Familiar patterns can be applied without examining the task.|principles~They guide trade-offs at a broader level than a component specification.~They are interchangeable with precise implementation rules.
111|logistics~Recruitment and access constraints affect whether the plan is executable.~Method selection alone makes the plan ready.|analysis planning~Decide how evidence will answer the question.~Leave analysis unspecified until all data is collected.|decision linkage~The plan needs time and authority to influence a choice.~Delivering a report is the complete research outcome.
112|operational causes~Capacity and incentives may produce visible interface complaints.~Every complaint about an app originates in its screens.|stakeholder accounts~Compare them with observed work and other evidence.~Treat the most senior account as ground truth.|research scope~Include people who deliver and coordinate the service.~Customer interviews reveal all backstage mechanisms.
113|competitive evidence~Visible choices can inspire hypotheses, not prove success.~Market prominence validates every interaction.|unknowns~Capacity, economics, and outcomes may remain invisible.~Screens disclose the complete operating model.|transferability~Check whether the competitor’s context matches yours.~A successful-looking pattern transfers unchanged.
114|neutral probes~Ask what happened next and what the person did.~Suggest the intended cause and ask for agreement.|memory limits~Treat retrospective accounts as situated recollection.~Treat every remembered detail as a complete event record.|episode detail~Concrete sequence can reveal constraints behind a choice.~A broad satisfaction statement supplies the same evidence.
115|tacit work~Observation can reveal actions people omit in accounts.~People can always describe every routine adaptation.|research disruption~Protect important work and consent during observation.~Interrupt whenever an interesting event occurs.|workarounds~Investigate the need and risk before proposing removal.~Enforce the documented process immediately.
116|longitudinal fit~Use it when change or recurring context matters.~A longer study automatically answers a better question.|missing entries~They may reflect burden or selective reporting.~They prove the relevant experience did not occur.|reactivity~Repeated prompts can change attention or behaviour.~Recording experience cannot affect the experience.
117|construct validity~The question must measure what the decision actually needs.~Any satisfaction question can represent future usage.|sample quality~Who responds affects what can be inferred.~Large numbers eliminate selection bias.|stated preference~It does not guarantee behaviour under real constraints.~Strong agreement forecasts adoption directly.
118|abandonment meaning~Some exits may be successful or continue elsewhere.~Every exit is a failure of the last screen.|mechanism evidence~Combine event patterns with contextual investigation.~The funnel alone explains the cause.|instrumentation limits~Unrecorded channels can change the interpretation.~No event means no subsequent progress occurred.
119|shared discovery~Disciplines should influence framing while alternatives remain open.~Engineering participation begins after design approval.|constraints~They can reveal new opportunities rather than only block ideas.~They should be considered only during estimation.|team rituals~They matter when they change evidence use and decisions.~A scheduled trio meeting is proof of good discovery.
120|tree structure~It separates outcome, opportunity, solution, and assumption.~It is a hierarchy of approved features.|causal humility~The real system may contain feedback and shared dependencies.~The tree proves a simple causal relationship.|tree maintenance~Update it when evidence changes the reasoning.~Keep it stable so earlier decisions look consistent.
121|cadence purpose~It keeps evidence close to decisions.~It maximises interview frequency.|reviewing evidence~It can expose a gap without new collection.~Existing evidence should be ignored once a sprint ends.|decision windows~Plan learning when it can affect commitment.~Research timing can be independent of delivery decisions.
122|participant stewardship~Recruitment, consent, and data handling are operational responsibilities.~ResearchOps is only calendar administration.|reuse~Evidence needs context, permissions, and retrievability.~Any stored note is automatically reusable.|standardisation~Support consistency without erasing contextual judgement.~Require identical methods for all research questions.
123|theme traceability~Keep links to the episodes supporting a claim.~A label on a cluster is enough evidence.|contradiction~It may narrow the claim or reveal another mechanism.~It should be discarded if it occurs infrequently.|evidence strength~Consider quality and relevance, not only quantity.~A large cluster is necessarily a strong insight.
124|source disagreement~Check population, definitions, timing, and visibility.~Resolve it by voting among sources.|triangulation~It tests explanations through complementary evidence.~It means forcing every source to tell one story.|scope~Two apparently conflicting findings may apply to different conditions.~Different results prove one method is unreliable.
125|representativeness~A story illustrates a pattern only within an evidenced boundary.~A vivid case is representative by default.|prevalence~It needs suitable evidence beyond narrative strength.~Audience recall of a story establishes prevalence.|communication~Keep the context that makes the mechanism understandable.~Strip context to make the story universally applicable.
126|consistent claims~The underlying evidence and confidence should survive format changes.~Executives should receive a more certain version.|audience needs~Adapt detail to the decision the audience faces.~Give every audience identical material regardless of use.|uncertainty~It can be concise without disappearing.~Short formats justify removing confidence limits.
127|content authority~Identify which version is authoritative before reorganising it.~Preserve all duplicates to avoid deciding ownership.|currency~Outdated promises can create service failures.~Age is irrelevant if a page still receives traffic.|inventory purpose~Use it to decide retention, repair, ownership, and structure.~Treat the page count as the main deliverable.
128|structured facts~A shared model reduces contradictory copies.~Copying facts across pages is the safest reuse strategy.|relationships~They express how content objects connect.~A visual page template fully defines those relationships.|ownership~Authoritative facts need update responsibility.~Structure alone keeps information current.
129|organisation schemes~Task and topic schemes answer different seeking needs.~One scheme is best for every content collection.|ambiguous categories~Test where people expect content and allow useful cross-paths.~Assume every item has one obvious home.|audience schemes~They can fail when people cannot identify with a category.~Audience labels are always easier than task labels.
130|synonyms~They connect language variation to the intended concept.~They mean every similar word is interchangeable.|controlled terms~They support consistency while retaining necessary distinctions.~They require all users to learn internal language.|vocabulary governance~Update terms as usage and services change.~A published vocabulary should never change.
131|orientation~People need to understand where they are and what is nearby.~Only the next button matters.|entry points~Navigation should work for people arriving mid-structure.~Every session begins at the home page.|hierarchy~It can expose relationships without displaying every item at once.~Good navigation requires all destinations to remain visible.
132|facets~They help narrow results along meaningful attributes.~Any available database field makes a useful facet.|no-results recovery~Explain and offer useful reformulation or alternatives.~An empty list is sufficient feedback.|ranking~Relevance needs to fit the task and context.~Popularity is always the best relevance signal.
133|metadata~It describes attributes that support use and retrieval.~It is merely another word for categories.|ontology~It models meaningful relationships between concepts.~It is simply an alphabetical list of tags.|folksonomy~User-created tags can reflect language but vary in consistency.~User tags automatically form a controlled vocabulary.
134|link context~Nearby information can strengthen destination prediction.~Only the clickable words affect scent.|ambiguous labels~They increase uncertainty before navigation.~They improve discovery by encouraging curiosity.|evaluation~Observe whether people choose a promising path and recover.~Measure only the number of clicks generated.
135|sitemaps~They show structural relationships between destinations.~They capture every action and recovery state.|wireflows~They connect interface states to interaction paths.~They are equivalent to a gallery of separate screens.|artefact choice~Use the representation that exposes the current uncertainty.~Use the most polished format regardless of the question.
136|change governance~Ownership and migration keep the structure coherent.~A launch sitemap is sufficient long-term governance.|content growth~New material can strain categories and labels.~An initially sound structure stays sound at any scale.|review loops~Use evidence of finding problems to revise the architecture.~Reorganisation should follow only internal departmental changes.
137|content strategy~It connects needs, states, channels, and lifecycle decisions.~It is the brand’s tone guide alone.|empty states~They should explain the situation and useful next action.~They are only opportunities for decorative messaging.|maintenance~Content needs owners as the service changes.~Approved wording remains valid indefinitely.
138|plain language~It helps people understand and act, not merely read fewer words.~It is achieved by minimising character count.|technical precision~Explain necessary concepts in familiar language without changing meaning.~Replace technical terms with unexplained abbreviations.|testing clarity~Check understanding in the relevant task.~A readability score alone proves comprehension.
139|voice and tone~A consistent voice can adapt tone to consequence and emotion.~Consistency requires identical tone in every situation.|failure messages~Useful facts and recovery take priority over personality.~A witty message is preferable if it increases engagement.|empathy~It should be supported by an effective next step.~Warm language is sufficient even when no help exists.
140|semantic order~Meaning should survive alternative reading sequences.~The visual layout alone defines reading order.|multimodal access~Essential content needs usable alternatives.~Alt text is unnecessary if the illustration is attractive.|content relationships~Labels and structure should be programmatically meaningful.~Spatial proximity alone communicates every relationship.
141|wording effects~Labels can change predictions of consequence and reversibility.~Words do not affect behaviour if the button position stays fixed.|content experiments~Observe comprehension and action appropriate to the risk.~Use preference votes as the only outcome.|truthfulness~Copy must reflect actual system behaviour.~Clear copy can safely promise an unsupported outcome.
142|policy change~Trace every affected message and channel.~Update only the most visited page.|verification~Check that the intended change actually reached production.~Approval of the draft establishes publication correctness.|responsibility~An owner needs a review and update process.~A shared document makes ownership unnecessary.
143|cross-channel truth~Adapt presentation without changing the underlying state.~Each channel can simplify the state differently.|notifications~They should remain consistent with current authoritative information.~The last sent message always represents the current state.|support language~Staff need the same meaningful state distinctions.~Only the app needs consistent terminology.
144|pattern assumptions~They concern the task, state, and expectations as well as appearance.~Visual familiarity guarantees behavioural fit.|transfer~Check where the new context differs from the original.~Copying a common pattern removes the need for evaluation.|exceptions~The pattern needs a safe response to actual failure modes.~Matching its happy path is sufficient adoption.
145|interaction medium~Choose for context, abilities, privacy, and precision.~Use the newest medium to signal innovation.|voice~It can be unsuitable in noisy or private contexts.~It is universally easier than touch.|touch~It requires appropriate targets and conditions of use.~It is suitable wherever a screen can be installed.
146|shortcut discovery~Visible commands and hints can support learning.~Hidden shortcuts are self-explanatory to all experts.|consistency~The shortcut should preserve the visible command’s meaning.~A shortcut may have a different consequence to save time.|risk~Efficiency needs safeguards for consequential actions.~Fewer keystrokes is always the best design.
147|selection scope~People need to know which items an action will affect.~A selected count is sufficient even when membership changes.|changing lists~Reconcile selection and freshness before commitment.~Keep selections silently even when the underlying records change.|bulk recovery~A mistake may affect many records and needs appropriate protection.~The same protection as a harmless single-item action is always enough.
148|save state~Make persistence and unsaved work understandable.~A visually complete form implies it has been saved.|conflict~Explain and help resolve competing versions.~Silently overwrite older work to avoid complexity.|preview~It helps inspect consequences but does not replace saving.~A correct preview proves the content is durably stored.
149|before action~Show consequence so the person can make an informed choice.~Explain consequence only after submission.|after action~Represent the actual result or uncertainty.~Always show success immediately to maintain momentum.|timing~The right information needs to arrive before the relevant decision.~Useful information is effective regardless of when it appears.
150|contextual learning~Guidance is easier to use near the relevant task.~All instruction should appear before the first action.|repeat access~Help should remain available when knowledge fades or tasks change.~A dismissed tip never needs to be recoverable.|expert support~Avoid repeatedly blocking familiar work with basic instruction.~Every session should repeat the full onboarding tour.
151|baselines~They make magnitude and change interpretable.~A rising line establishes meaningful improvement by itself.|uncertainty~It affects what decisions the chart supports.~It should be removed because it complicates presentation.|definitions~Viewers need to know what the measure represents.~A metric’s label has one obvious meaning to everyone.
152|shared state~People need to understand changes made by others.~Presence indicators alone explain all collaboration.|conflict resolution~Protect work and make reconciliation understandable.~The newest timestamp is always the fairest resolution.|identity~Actions need appropriate attribution and authority.~Any signed-in collaborator should be able to make every change.
153|system users~Include people implementing, maintaining, and governing the system.~Designers are its only relevant audience.|needs research~Observe recurring work and adoption barriers.~Treat requested component counts as the whole need.|system value~It should improve useful work and resulting products.~It succeeds when its catalogue is large.
154|semantic tokens~They connect design intent to consistent implementation meanings.~They are simply colour values with arbitrary names.|specifications~Include behaviour and content, not just geometry.~Matching dimensions guarantees system parity.|production checks~Verify that the implementation preserves the contract.~The design file is the final evidence of correctness.
155|versioning~Communicate compatibility and migration implications.~A new version number is enough guidance.|exceptions~Make them owned and reviewable.~Allow every exception to become an invisible permanent fork.|contribution~Provide a practical route for teams to improve shared work.~Require central authors to anticipate every local need.
156|defect propagation~Shared components can distribute a flaw widely.~Reuse automatically guarantees accessibility.|integration testing~A sound component can still be used incorrectly in context.~Component-level checks eliminate all product-level testing.|quality contracts~Specify states, access behaviour, and evidence.~Specify only the default visual result.
157|ecosystem boundaries~Include actors affected without directly using the product.~Limit the map to account holders.|power~Different actors have unequal influence and exposure to harm.~Every stakeholder has an equivalent role.|dependencies~They reveal where value or responsibility can break.~They are background context unrelated to design decisions.
158|delay research~Trace queues, information, policy, and capacity.~Ask only whether the waiting screen is clear.|frontline evidence~It can explain operational mechanisms customers cannot see.~Customer accounts reveal every backstage cause.|intervention choice~Match the change to the cause established by evidence.~Begin with a new tracking interface in every delay problem.
159|capacity~It determines which promises can be reliably made.~It is separate from experience design.|policy~It shapes the actions and exceptions available to people.~It only matters after interface design is finished.|honest promises~Communicate uncertainty and available help when delivery is constrained.~Maintain ideal promises to avoid discouraging use.
160|averages~They can conceal people left waiting much longer.~A lower mean implies everyone benefits.|staff burden~It can increase when digital effort appears to decrease.~It is outside the user experience measurement scope.|cross-channel outcomes~Measure whether the need was resolved, not merely transferred.~A transfer out of the app counts as completion.
161|equity~Consider actual burden and outcome under differing circumstances.~Identical steps guarantee equal opportunity.|distribution~A positive aggregate may hide harms to a subgroup.~Overall gain is sufficient evidence of inclusion.|recourse~People need workable alternatives when the standard route fails.~A nominal help link establishes equitable recovery.
162|alternatives~Keep materially different approaches available while learning.~Produce many cosmetic variants of one solution.|selection criteria~Use explicit goals, evidence, and constraints.~Choose whichever concept looks most finished.|convergence timing~Narrow when evidence supports commitment.~Keep every idea equally active until launch.
163|sketching~It externalises assumptions that abstract agreement can hide.~Its purpose is to prove drawing skill.|shared scenarios~They allow comparisons of how different proposals handle the same conditions.~Different scenarios make alternatives automatically comparable.|early fidelity~Rough work can expose behaviour before visual commitment.~Polish is required before useful discussion can occur.
164|behavioural fidelity~Simulate the dependency that determines the research question.~Visual realism is always the priority.|waiting~Realistic delay may reveal behaviours instant prototypes miss.~An instant response adequately tests all waiting experiences.|staff judgement~Represent it when it changes the service outcome.~Replace every judgement with automatic success during testing.
165|critique questions~Connect observations to intent and consequences.~Collect likes and dislikes as the principal evidence.|evidence boundaries~Separate known effects from plausible concerns.~Present every concern as an established usability failure.|decision authority~Clarify how critique will influence the next choice.~Assume the most senior preference is the outcome.
166|method coverage~Different risks may need different evidence sources.~One usability study resolves every product risk.|scope~Specify people and conditions the findings cover.~Any user evaluation generalises to every audience.|strategy updates~Adapt evaluation when uncertainty or consequence changes.~Keep the original plan regardless of emerging risks.
167|moderation~It can support probing, adaptation, and participant welfare.~It is merely a slower version of unmoderated testing.|unmoderated tasks~They need enough clarity to work without live repair.~The moderator can fix unclear instructions afterward.|research risk~Method choice must consider participant consequences.~Remote participation removes ethical responsibilities.
168|predictive estimates~They address bounded aspects of performance under assumptions.~They predict the full experience including trust.|skilled behaviour~Models may assume familiarity absent in beginners.~Estimates apply unchanged at every expertise level.|complementary research~Observe understanding and context outside the model’s scope.~A model calculation makes field evidence unnecessary.
169|severity~Consequence matters even when an issue is uncommon.~The most frequent issue is always the most severe.|confidence~It affects how firmly to act or what to investigate next.~It should be ignored once a recommendation exists.|dependencies~Some fixes enable or constrain others.~Rank each fix independently of the surrounding system.
170|inputs and outputs~Work invested and things shipped differ from user outcomes.~Shipping more necessarily creates more value.|guardrails~They constrain unacceptable side effects.~They are optional metrics used only if the primary metric falls.|team targets~They should reflect influence and avoid harmful local optimisation.~Every team should maximise the same event count.
171|North Star~It expresses an enduring direction for value.~It replaces all operational and safety measures.|focused metrics~A stage-specific priority can change as uncertainty changes.~One metric should remain the sole focus forever.|guardrail role~Focus should not hide exclusion or harm.~A rising focus metric overrides all contrary evidence.
172|cohorts~Comparable groups and time windows support meaningful comparison.~Any two groups can be compared without exposure context.|retention~It measures return behaviour, whose value depends on the service.~More returns always mean a better user outcome.|funnels~They show recorded progression, not the full cause of exits.~A drop at a step proves that step caused abandonment.
173|confounding~A third factor can affect both the proposed cause and outcome.~A strong correlation excludes third-factor explanations.|causal evidence~Design and assumptions determine what can be inferred.~Statistical association alone establishes intervention benefit.|observational use~It can generate and constrain hypotheses while retaining limits.~It has no value unless it proves causation.
174|assignment units~They should account for shared staff or clinic effects.~Patient-level randomisation is always independent.|spillover~Treatment can affect people outside its assigned group.~It cannot occur when the interface is shown individually.|analysis units~They must reflect dependence and the experiment’s design.~Every event can be treated as an independent observation.
175|meaningful effect~Define practical importance before interpreting significance.~Any statistically detectable change is practically valuable.|sensitivity~Plan whether the test can detect the effect that matters.~A non-significant result always proves no useful effect exists.|stopping rules~Prespecification supports valid interpretation.~Stop whenever the preferred result appears.
176|event semantics~Different systems need agreed state definitions.~Identical event names ensure identical meanings.|reservation versus acceptance~They represent different commitments and should remain distinguishable.~They can be merged to simplify the success metric.|data verification~Check whether recorded events reflect actual transitions.~Successful transmission proves measurement validity.
177|learning culture~It preserves invalid and negative results as well as positive ones.~It celebrates only tests that show a win.|decision response~Evidence should change choices when warranted.~Running tests is valuable even if decisions never change.|validity~A smaller set of trustworthy tests can teach more than many flawed ones.~Test volume is the strongest maturity indicator.
178|cumulative burden~Manageable steps can combine into an exclusionary journey.~Passing each screen individually guarantees inclusion.|dependency chains~Access may require resources acquired outside the interface.~Only demands visible on the current screen matter.|whole-journey evaluation~Follow effort and failure across transitions.~Stop evaluation after the first successful task.
179|edge experiences~They can reveal hidden assumptions without representing everyone.~One edge participant speaks for all excluded people.|co-design power~Participants need the possibility of influencing decisions.~Attendance at a workshop establishes shared power.|participation support~Compensation and accessible methods affect who can contribute.~Equal invitations create equal participation conditions.
180|approach distinctions~Design traditions overlap but differ in aims and decision power.~Their names describe interchangeable processes.|universal ambition~It does not remove the need to examine specific exclusions.~It proves every person’s needs are met.|method combinations~Choose them for the actual question and limitations.~Pick one label and avoid all other practices.
181|automated checks~They identify a subset of possible accessibility failures.~A clean scan establishes conformance.|scope statements~They define what pages, states, and criteria were evaluated.~A conformance claim does not need a boundary.|manual evidence~Keyboard and assistive-technology checks address gaps in automation.~They add no value after automated testing passes.
182|regressions~New content and code can break previously accessible behaviour.~A passed review remains valid after any update.|ownership~Someone needs responsibility for detection and repair.~A shared commitment is enough without response ownership.|monitoring~Combine checks and feedback with a repair loop.~Wait for a major complaint before investigating.
183|necessity~Collection should have a specific justified purpose.~Potential future analysis makes any field necessary.|lifecycle~Retention, access, and deletion affect proportionality.~Only the initial collection moment matters.|refusal~Consider what happens when people cannot or will not provide data.~Making a field optional settles every privacy issue.
184|equal rules~They can impose unequal practical burdens.~They guarantee equitable outcomes.|power~It affects whose needs and objections shape decisions.~It is unrelated to interface design.|remedy~Assess whether affected people can actually challenge and repair harm.~An explanation alone provides complete recourse.
185|escalation authority~A concern needs an accountable route to change or pause work.~Permission to speak is sufficient even if nobody can respond.|junior participation~Protect the ability to raise evidence without retaliation.~Treat rank as a proxy for evidence quality.|decision records~Document the concern, response, owner, and unresolved risk.~Record only that a discussion occurred.
186|AI storyboards~Include failures and uncertainty as well as success.~The ideal output is a complete experience model.|role allocation~Make human and system authority explicit.~Let responsibility emerge after implementation.|handoff design~Specify what information and control transfer.~A human-in-the-loop label defines the handoff sufficiently.
187|feedback loops~System outputs can alter future behaviour and inputs.~The input distribution is unaffected by deployment.|workflow change~AI can redistribute effort and responsibility.~It is a neutral replacement for an isolated component.|system evaluation~Trace downstream consequences as well as interface use.~Stop evaluation at the generated output.
188|metaphor expectations~A teammate metaphor may imply competence or responsibility the system lacks.~Anthropomorphic language has no effect on reliance.|capability boundaries~They should constrain how the feature is described.~Marketing personality can safely exceed actual capability.|accountability~Responsibility remains with real people and organisations.~A named AI persona can bear operational responsibility.
189|citation support~Check that the source actually supports the claim.~A real URL establishes factual correctness.|applicability~A valid source may be outdated or irrelevant to the person’s context.~Authoritative sources apply unchanged in all contexts.|recourse~People need a way to challenge or recover from a faulty answer.~Citations remove the need for recovery design.
190|prediction versus action~A probability needs a policy before it becomes an intervention.~The highest score is automatically the appropriate action.|thresholds~Consequences and uncertainty should influence them.~One threshold works for every risk level.|review capacity~A policy requiring review must have realistic resources.~Adding human review on paper is sufficient protection.
191|affected non-users~They can bear consequences without touching the feature.~They fall outside user research scope.|operators~Their incentives and workload influence outcomes.~Only recipients’ preferences matter.|scope expansion~AI may change who needs to be researched.~Keep the original interface audience as the permanent boundary.
192|AI synthesis~Trace claims to evidence and inspect omissions and contradictions.~Fluent themes can be accepted without checking notes.|research responsibility~The researcher remains accountable for interpretation.~Responsibility transfers to the tool provider.|authorised data~Use and disclosure constraints still apply during synthesis.~Using AI makes all stored research available for reuse.
193|RITE scope~It supports rapid response to observed usability issues.~It establishes long-term product value.|iteration evidence~Changes between sessions affect comparability.~All sessions remain directly comparable after any change.|method selection~Use other designs for questions RITE cannot answer.~Faster iteration replaces the need for causal evaluation.
194|trustworthiness~It depends on deployed controls and their effectiveness.~A model benchmark certifies the whole product.|operational ownership~Controls need people who monitor and act.~A published principles page is sufficient governance.|evidence~Test whether safeguards work in relevant conditions.~The existence of a safeguard proves protection.
195|agreement rates~They can reflect deference rather than correctness.~More agreement always means better recommendations.|review independence~Check whether reviewers can detect and challenge errors.~Count approvals as evidence of effective scrutiny.|review resources~Time, information, and authority affect oversight.~Nominal responsibility guarantees meaningful review.
196|accountability~It differs from contributing expertise or being consulted.~Everyone consulted automatically has final authority.|decision rights~Clarify who resolves disagreement and owns consequences.~Let authority follow whoever speaks most confidently.|expertise~It informs the decision without necessarily owning it.~The most specialised person must own every related decision.
197|delivery learning~Allow evidence to revise scope and assumptions.~Estimation makes the assumptions fixed facts.|commitment management~Make the consequences of new evidence explicit.~Protect the schedule by recording but ignoring contrary findings.|shared ownership~People need an agreed route to change the plan.~Sending research links is a complete learning loop.
198|minimum scope~It should preserve the conditions for credible learning.~Any small release is a valid MVP.|ethical minimums~Safety and consent cannot simply be removed to save time.~A test label excuses avoidable participant risk.|value hypothesis~Specify what the release is meant to establish.~Adoption alone answers every product question.
199|problem evidence~It concerns whether the need matters, not just whether the flow works.~Usability success proves the need is worth solving.|solution evidence~It tests whether this intervention works for the task.~Stated demand validates the interface.|outcome evidence~It follows actual consequences beyond prototype performance.~A successful prototype establishes long-term impact.
200|partial failure~Identify and help people affected before or during a pause.~Turning the feature off resolves every consequence.|resumption~Use evidence that the failure is contained and controls work.~Restart once the launch deadline demands it.|rollout design~Plan detection, ownership, rollback, and repair in advance.~Deployment tooling alone is a complete rollout plan.
201|substitution expectations~They shape the promise before checkout, not only after fulfilment.~They are solely an operational issue after payment.|incentives~Fulfilment choices may conflict with what customers expect.~The interface can be evaluated independently of picking incentives.|recovery~Offer workable control when delivered items differ from expectations.~A completed payment is sufficient evidence of a good journey.
202|enterprise density~Structured detail may be necessary for expert comparison.~Removing information always improves usability.|roles~Permissions and responsibilities shape safe workflows.~One interaction model fits every organisational role.|exceptions~Support unusual but consequential work explicitly.~Optimise only the common path because experts can improvise.
203|cross-channel state~Digital and telephone changes need coherent authoritative meaning.~Each channel can keep an independent confirmation model.|staff capacity~Promises depend on the people who must fulfil them.~Good content can compensate for unavailable capacity.|recovery ownership~Someone must handle failed or conflicting appointment changes.~A general help page is sufficient operational recovery.
204|completion limits~A completed form can still produce an incorrect or inequitable decision.~High completion is sufficient evidence of safety.|appeal and remedy~People need usable routes to challenge and repair adverse outcomes.~An explanation removes the need for appeal.|evidence quality~Authority, currency, and applicability matter together.~Any cited document makes a decision defensible.
`;
export const extraChecks=Object.fromEntries(rows.trim().split('\n').map(line=>{
  const [number,...checks]=line.split('|');
  return ['UX-'+number,checks.map((entry,i)=>{
    const [topic,answer,distractor]=entry.split('~');
    if(!topic||!answer||!distractor)throw new Error('Incomplete check '+number);
    const correct=(Number(number)+i)%2;
    return {prompt:`When considering ${topic}, which statement is more accurate?`,options:correct?[distractor,answer]:[answer,distractor],correct,explanation:answer,topic};
  })];
}));
if(Object.keys(extraChecks).length!==204||Object.values(extraChecks).some(q=>q.length!==3))throw new Error('Expected three additional checks for every lesson');
