// Each row: lesson number | best answer | misconception | misconception | explanation.
// Option order is rotated deterministically; the correct position is not fixed.
import { recallPrompts } from './recall-prompts.mjs';
const rows = `
001|Follow Maya’s goal, the service handoff, and whether she actually gets an appointment.|Judge the experience from the confirmation screen alone.|Treat a submitted request as the completed user goal.|A request is one system event. UX includes the whole attempt and the uncertainty left afterward.
002|Observe representative people completing the same tasks in relevant contexts.|Ask the design team which screen looks more professional.|Choose the version with the fewest controls.|Usability depends on people, goals, and context. Visual preference and control count cannot establish task success.
003|Measure successful booking and investigate whether Maya understands and feels confident about the outcome.|Use completion time as the measure of both usability and reassurance.|Replace the success measure with a visual preference rating.|Task performance and felt experience are related but distinct. Speed alone does not establish confidence.
004|Investigate interruptions, connectivity, movement, and privacy before changing the flow.|Shrink the desktop layout and keep the same interaction assumptions.|Conclude that the participant needs more practice.|The context changes the resources available to act. A responsive layout alone does not address those conditions.
005|Trace delivery, receipt, ownership, and acknowledgement across the app and clinic.|Improve the visual prominence of the sent message.|Assume the clinic has the referral because the app logged a send event.|Sending is not receiving. The service handoff needs evidence and an accountable owner.
006|Check correct outcomes, understanding, recovery, and the work shifted to support.|Declare success because more people completed the flow.|Treat support calls as unrelated to the digital experience.|A local improvement can transfer effort or uncertainty elsewhere. Completion is only one quality signal.
007|Check attention, task relevance, comprehension, and the action the banner supports.|Assume visible information has been noticed and understood.|Increase saturation before investigating the person’s task.|Visibility is not perception. Attention is selective, and noticing still does not guarantee understanding or action.
008|Group related information and separate unrelated actions to communicate their relationships.|Use identical spacing between every element for consistency.|Rely on explanatory text to override contradictory visual grouping.|People infer relationships from layout before reading every word. Spacing and alignment carry meaning.
009|Help the person recover their goal, current state, and unfinished work.|Measure interruption cost only by its duration.|Restart the task so everyone returns to a known state.|Resumption requires reconstructing context. Preserved work and clear state reduce that extra burden.
010|Keep selected clinics and decision-relevant attributes visible for comparison.|Ask people to remember each clinic’s details across separate pages.|Show every available attribute at once.|Recognition reduces memory demands, but useful comparison still needs prioritisation rather than indiscriminate display.
011|Use a default only with a defensible user benefit, visible consequences, and an easy change.|Choose the option that maximises acceptance without testing its effects.|Treat a preselection as neutral because it can be changed.|Defaults influence decisions. Reversibility helps, but does not make an unsuitable default harmless.
012|Check the authoritative submission state and provide a safe retry that cannot duplicate the request.|Immediately ask Maya to submit again.|Show a success message because the button was pressed.|A lost response does not reveal whether the action completed. Recovery must handle that uncertainty safely.
013|Keep the goal stable while considering different tasks and interface actions that could support it.|Define the goal as clicking the booking button.|Treat the current screen sequence as the only valid strategy.|Goals describe intended progress. Tasks and actions are means that can change without changing the goal.
014|Investigate both expectations and expose the real state and next responsibility.|Use the clinic’s internal terminology everywhere.|Train Maya to memorise every internal status.|Mental-model mismatches need investigation and a understandable system representation, not merely internal labels.
015|Specify objects, relationships, states, and permissible actions.|Start with the colours and positions of the screens.|Use referral and appointment interchangeably to reduce terminology.|A conceptual model makes the system predictable. Distinct objects and states need distinct meanings.
016|Use the queue metaphor only where order, progress, and exceptions match the service.|Imply first-come-first-served processing even when priority varies.|Assume a familiar metaphor cannot mislead.|A metaphor carries expectations. Those expectations must match real behaviour or be explicitly qualified.
017|Model decisions, exception work, staff handoffs, and recovery beyond the screens.|Document only the successful sequence of taps.|Treat work outside the app as outside the design problem.|The activity continues across people and channels. A screen flow cannot represent the whole workflow.
018|Investigate whether the call reflects uncertainty, a failed handoff, or another need before specifying a solution.|Build a dashboard because the call proves one is missing.|Add a call button without understanding the reason for calling.|The same behaviour can have different causes. Requirements need a defensible interpretation of evidence.
019|Connect the uncertainty to a decision owner, deadline, and results that would change the choice.|Ask which design users like best without naming a decision.|Collect broad feedback after the choice is irreversible.|A useful research question reduces uncertainty while the evidence can still affect a decision.
020|Test the assumption whose failure would most undermine the proposal.|Test the easiest assumption first to show progress.|Treat demand as sufficient evidence that clinic transfer will work.|Desirability, feasibility, service capacity, and other assumptions can each invalidate the idea.
021|Choose methods for the claim needed: accounts, observed behaviour, prevalence, or causal effect.|Use interviews to establish population prevalence.|Use a preference survey to establish a causal effect.|Methods support different kinds of inference. Their evidence is not interchangeable.
022|Recruit across conditions that could change the finding, including people excluded by the current flow.|Use colleagues because they understand the product.|Recruit only frequent successful users.|Convenient participants can omit the conditions that create failure. Sampling should follow the research question.
023|Explain purpose, data use, risks, voluntary participation, and withdrawal in understandable terms.|Treat a signature as sufficient regardless of comprehension.|Collect everything now and decide its purpose later.|Consent is an informed and continuing choice, alongside responsible data handling.
024|Keep what happened separate from why it happened and what the team proposes to change.|Present a preferred solution as an observed finding.|Treat one plausible explanation as established fact.|Each inference needs support. Separating evidence, interpretation, and action makes the reasoning challengeable.
025|Maintain regular contact that can change assumptions and upcoming decisions.|Repeat interviews weekly regardless of what has been learned.|Finish discovery once the roadmap is approved.|Continuity is about decisions responding to learning, not a meeting frequency alone.
026|Trace comparison through availability, acceptance, and access to care.|Measure success by the feature shipping on schedule.|Assume more comparison clicks mean better access.|Outputs do not guarantee outcomes. The causal chain can fail after interaction with the feature.
027|Reconstruct a recent real episode and probe actions, constraints, and consequences.|Ask whether the person would use an ideal future feature.|Describe the solution before asking what they need.|Concrete episodes reveal behaviour and context that hypothetical enthusiasm cannot establish.
028|Separate desired progress, an unmet need, and a proposed intervention.|Put features directly under the outcome and label them needs.|Define the opportunity as building clinic comparison.|The separation keeps multiple solutions available for the same underlying opportunity.
029|Isolate the risky assumption and choose a test whose result could refute it.|Test the complete polished experience without identifying the assumption.|Choose the smallest prototype regardless of what it can reveal.|A small test is valuable only if it produces credible evidence about the important uncertainty.
030|Record the choice, alternatives, evidence, uncertainty, owner, and revisit condition.|Record only the approved solution.|Remove rejected alternatives to keep the record concise.|Decision records preserve reasoning so later teams can understand and revise the commitment.
031|Look for a recurring mechanism in context, including its consequence and exceptions.|Count repeated words and call the largest group a theme.|Use the most memorable quotation as the theme.|A theme is an explanatory pattern, not a word-frequency cluster or vivid anecdote.
032|State the inference from the call and seek evidence that could challenge it.|Treat the call as proof that all patients share the same problem.|Skip interpretation and jump directly to a feature.|Insights extend beyond observations. Their inferential step and confidence should remain visible.
033|Include evidence-backed differences that change a design decision.|Add fictional demographic detail to make the persona vivid.|Use one average persona for every task and circumstance.|A persona earns its place through decision-relevant behavioural and contextual distinctions.
034|Describe the goal, situation, constraints, sequence, and consequences of an interruption.|Describe only the intended button presses.|List persona attributes without a situation.|Scenarios make conditions and exceptions concrete enough to influence requirements.
035|Use a journey for the person’s experience and a blueprint for the operational dependencies behind it.|Use a journey map to assign every backstage system dependency.|Use either map interchangeably because both have a timeline.|The maps answer different questions. A blueprint connects experience to service delivery.
036|Tell a concrete story while stating evidence, limits, and the decision it informs.|Remove uncertainty to make the presentation persuasive.|Let the emotional strength of a story imply prevalence.|A memorable narrative should preserve, not inflate, the evidence behind its claims.
037|Align organisation, labels, and navigation with how people seek the content.|Add more content to compensate for poor findability.|Assume accurate content is automatically discoverable.|Content quality and findability are separate requirements that must work together.
038|Use a label that predicts the destination in the audience’s vocabulary, then test it.|Prefer internal terminology because it is precise to staff.|Choose the shortest label without checking interpretation.|A useful label sets the right expectation before someone follows it.
039|Show location, relevant alternatives, and a safe path back or onward.|Assume everyone arrived from the home page.|Force every deep-link visitor to restart navigation.|People enter information spaces at different points. Orientation must work from those entry points.
040|Show a descriptive title, relevant context, and attributes that help judge the match.|Make every result description the same length and wording.|Hide useful attributes until after the result is opened.|Information scent lets people estimate relevance before spending effort on the next step.
041|Name the action and its real consequence, including whether it sends a request or confirms a booking.|Use a generic action label because it fits every state.|Say Confirm when the system only sends a request.|Words shape expectations and must match the authoritative system action.
042|Explain what failed, what was preserved, and the safe next action.|Show an error code as the only explanation.|Ask for a retry without checking whether the first attempt succeeded.|Recovery content needs to resolve uncertainty, not merely announce failure.
043|Match the interaction style to the task, environment, expertise, and need for precision.|Choose conversation because it feels more human.|Use direct manipulation for every kind of work.|No interaction style is universally best. Its fit depends on the activity and constraints.
044|Make the action discoverable, its consequence predictable, and its resulting state perceivable.|Rely on familiar visual styling without showing the resulting state.|Explain the action only after it has committed.|Controls need both feedforward and feedback to support informed action.
045|Ask only for information with a clear purpose at an appropriate moment.|Collect potentially useful fields while the person is already present.|Make every field optional instead of deciding whether it is needed.|Removing unnecessary demand is better than retaining questions without a defensible purpose.
046|Show acknowledgement, ongoing processing, and authoritative completion as distinct states.|Treat a disabled button as proof that the operation succeeded.|Display completion immediately to reduce anxiety.|Feedback must reflect what the system actually knows at each stage.
047|Prioritise the information and action needed for the next consequential decision.|Give all content equal emphasis to appear neutral.|Prioritise the most visually impressive component.|Hierarchy should follow the task and consequence, not equal decoration or visual novelty.
048|Reconsider context, input, comparison, interruption, and continuity as well as layout.|Scale every desktop element proportionally.|Remove secondary information even when it is needed for a safe decision.|Mobile use changes more than viewport width. Necessary information and task continuity still matter.
049|Combine reusable assets with shared behaviour, guidance, ownership, and maintenance.|Publish components and assume consistency will follow.|Standardise colours without examining service meanings.|A design system is a maintained organisational capability, not just an asset collection.
050|Specify keyboard, focus, loading, error, disabled, and recovery behaviour.|Approve the component from its default screenshot.|Leave exceptional states to each implementation team.|Real use includes state changes and failures. A component contract must cover them.
051|Define shared state meanings and wording across components and channels.|Allow every team to write its own confirmation message.|Rely on visual consistency to make different messages equivalent.|Semantic inconsistency can mislead even when components look identical.
052|Pilot with real teams and enough variation to reveal adoption and quality problems.|Migrate every product before gathering feedback.|Choose only a showcase with no demanding edge cases.|A useful pilot exposes real constraints while keeping the cost of revision manageable.
053|Include affected teams and define contribution, exceptions, versioning, and migration responsibilities.|Let the central team change shared behaviour without notice.|Require permanent uniformity with no exception process.|Shared changes need governance that preserves both coherence and practical adoption.
054|Measure whether adoption improves delivery and user-facing quality.|Use package installation counts as the quality outcome.|Count documented components regardless of actual use.|Adoption is an input signal. Its value depends on useful effects in products and work.
055|Connect each service promise to capable people, systems, policies, and an owner.|Treat a clear interface message as sufficient delivery.|Leave operational dependencies outside the design review.|A promise is reliable only when the service can fulfil it.
056|Make the service discoverable and understandable before judging completion inside it.|Evaluate only people who already found the service.|Treat finding the right service as a marketing issue alone.|People who cannot find or understand a service may be excluded before analytics records a task.
057|Verify the slot, records, staff capacity, and authority that make confirmation true.|Base confirmation on the front-end button event.|Assume a reassuring message can compensate for uncertain availability.|Frontstage claims depend on backstage conditions and authoritative state.
058|Expose the owner, system, information, and timing behind each handoff.|Add more emotion labels to the existing journey.|Assign responsibility to the patient whenever ownership is unclear.|Blueprinting makes operational gaps visible so they can be assigned and repaired.
059|Investigate why staff created the workaround and what it protects.|Remove the workaround immediately to restore process compliance.|Copy the workaround without checking its risks.|Workarounds are evidence about the actual service and its unmet operational needs.
060|Rehearse staffing, timing, handoffs, and failure conditions alongside the interface.|Infer service readiness from a successful screen test.|Use staff role-play only to approve visual details.|A service prototype tests whether the whole promise can be delivered under realistic conditions.
061|Make the uncertain behaviour realistic enough to answer the decision question.|Maximise visual fidelity before identifying the question.|Use the same prototype fidelity for every risk.|Fidelity is a means of obtaining relevant evidence, not a general quality score.
062|Retain evidence of the need while comparing alternative ways to meet it.|Treat a validated need as approval for the first solution.|Restart all research because one solution failed.|Need and solution validity are distinct. Evidence can support one while leaving the other unresolved.
063|Observe task outcome, understanding, errors, and recovery without leading the participant.|Count the intended clicks as success.|Ask whether the participant liked the flow after helping them finish.|Task completion can hide misunderstanding, and assistance can mask usability failures.
064|Use inspection to identify likely issues, then test claims about real use with appropriate evidence.|Treat expert agreement as proof of population behaviour.|Reject inspection because only user testing can find any issue.|Inspection is useful but has limits: it predicts problems rather than establishing all real-world effects.
065|Link the observation to consequence, context, confidence, and a proportionate action.|Report an isolated quote with a severity label.|Treat all observed issues as equally urgent.|Actionable findings explain why the issue matters and how strongly the evidence supports the response.
066|Choose changes around the uncertainty and preserve a way to interpret what improved.|Change every weak element simultaneously and infer which change helped.|Avoid iteration until the complete redesign is ready.|Focused changes can make learning clearer; broad changes obscure attribution.
067|Define the event’s actor, state, context, and downstream outcome before interpreting it.|Assume an event name has the same meaning in every system.|Treat a booking click as proof of care received.|Instrumentation must map to meaningful behaviour and state rather than ambiguous labels.
068|Choose an outcome criterion with guardrails for harms that must block release.|Use one aggregate score that lets gains cancel any harm.|Pick the metric most likely to show a positive result.|An overall criterion helps comparison but cannot replace explicit limits on unacceptable outcomes.
069|Separate the success outcome, explanatory signals, safety limits, and validity checks.|Treat every tracked event as a success metric.|Use a data-quality check as evidence of user value.|These measures serve different decisions and should not be conflated.
070|Specify the treatment effect for an assigned population, comparison, and outcome.|Use randomisation to claim the result applies to every future user.|Assume a positive result explains the psychological mechanism.|Randomisation supports a bounded causal estimate, not automatic generalisation or mechanism identification.
071|Check assignment, exposure, and comparable measurement before interpreting significance.|Trust the result because the p-value is low.|Adjust the success definition after seeing the result.|Statistical calculations cannot repair invalid assignment or inconsistent measurement.
072|Document the hypothesis, implementation, invalidity, and what can and cannot be learned.|Delete the experiment because it produced no usable lift estimate.|Report the favourable result with a small caveat.|Invalid tests still offer operational learning, but do not justify an unsupported causal conclusion.
073|Consider changing capability, environment, resources, and support across the journey.|Design for one average capability profile.|Treat accessibility needs as fixed traits of a separate group.|Exclusion can arise from temporary or situational mismatches as well as lasting impairments.
074|Compare the step’s sensory, cognitive, motor, and resource demands with people’s circumstances.|Classify people as capable or incapable of using the product.|Measure only how many fields are present.|A demand-capability mismatch identifies what the design or service should change.
075|Manage focus, keyboard access, semantics, announcements, and return from the dialog.|Make the dialog visually prominent and consider it complete.|Trap focus without providing a clear way to finish or cancel.|Operability requires a coherent interaction for assistive technology and keyboard users, not appearance alone.
076|Provide meaningful text, non-colour cues, and programmatic state with a clear action.|Increase colour saturation as the only status cue.|Use position alone to distinguish success and failure.|Meaning must survive changes in sensory channel or layout.
077|Check whether the choice supports informed goals and is easy to understand and change.|Judge the default by its conversion lift alone.|Assume any editable default preserves informed choice.|Manipulation can exploit attention or misunderstanding even when a theoretical opt-out exists.
078|Make purpose, refusal, later controls, and accountable data handling meaningful.|Treat acceptance as permanent permission for any future use.|Make refusal so costly that nearly everyone agrees.|Consent requires a real and understandable choice, not merely a recorded event.
079|Identify where inference adds value and compare a simpler non-AI alternative.|Add AI wherever the workflow contains text.|Assume automation is valuable because the model is accurate.|The need determines whether AI is appropriate; capability alone does not establish value.
080|Define bounded authority, visible actions, intervention, and recovery appropriate to the stakes.|Keep a human nominally responsible without time or power to intervene.|Require human approval for every action regardless of consequence.|Meaningful control depends on practical authority and usable intervention, not a human checkbox.
081|Help people predict capabilities, limits, uncertainty, and consequences.|Maximise confidence in every output.|Hide uncertainty to maintain trust.|Appropriate reliance is the aim. More trust is harmful when it exceeds actual capability.
082|Correct the claim, expose uncertainty, provide immediate recourse, and investigate the failure.|Offer a thumbs-down button as the only recovery.|Ask the person to retry until the model agrees.|Feedback collection does not itself repair harm or restore a safe path.
083|Evaluate model performance, task success, human behaviour, and real consequences together.|Use benchmark accuracy as the product success measure.|Use satisfaction alone because it reflects the full experience.|Product value and safety emerge from the whole human-system interaction.
084|Monitor changes in people, data, workflow, reliance, and outcomes with named response owners.|Watch one accuracy metric and assume the service is stable.|Treat post-launch monitoring as a model-team responsibility only.|Stable aggregate accuracy can conceal changing conditions and harms elsewhere in the system.
085|Describe the unmet progress and compare it with other opportunities using evidence.|Rewrite the requested feature as the problem statement.|Prioritise the request from the most senior stakeholder.|Opportunity framing separates the need from a proposed solution and makes alternatives comparable.
086|State a decision rule, its rationale, trade-off, and exception boundary.|Use a slogan that supports every possible choice.|Apply the principle regardless of context or consequence.|A principle helps resolve tension; it is neither decoration nor an unconditional rule.
087|Keep assumptions, evidence, and decision owners connected to delivery choices.|Freeze the design when implementation begins.|Collect new evidence but defer every response until after launch.|Delivery is another source of learning and must have a route to change commitments.
088|Explain the recommendation, alternatives, evidence, counterevidence, and trade-offs relevant to the audience.|Remove contrary evidence to make the argument clearer.|Tailor the confidence level to what the audience wants to hear.|Persuasion should make the reasoning usable without distorting its strength.
089|Align decision rights and shared service rules across teams.|Ask each team to optimise its own screen independently.|Resolve inconsistency through a shared colour palette.|Local optimisation cannot ensure coherent states, promises, and responsibility across the service.
090|Evaluate repeated use, operational cost, maintenance, recovery, and exit.|Treat launch adoption as the final value measure.|Ignore support burden when the interface performs well.|Value is created and lost over time, not only at release.
091|Trace tasks, behaviour, context, and competing explanations before judging the design.|Rank screenshots by visual polish.|Infer conversion from the prominence of a button.|A teardown forms evidence-aware hypotheses about an experience, not unsupported performance claims.
092|State the affected people, breakdown, consequence, and competing explanations without fixing the solution.|Frame the problem as the absence of the proposed feature.|Use the broadest possible problem so every idea fits.|A useful frame is specific enough to investigate while leaving solution alternatives open.
093|Link decisions and risky assumptions to methods, evidence thresholds, and timing.|List research activities without identifying their decision use.|Choose methods after committing to the solution.|A discovery plan is a learning strategy tied to decisions, not just an activity schedule.
094|Align data objects, state transitions, responsibilities, and interface promises.|Polish the interface to conceal inconsistent service states.|Treat data and policy as implementation details unrelated to UX.|A coherent experience depends on consistent meaning across the underlying system.
095|Map benefits and harms by affected group, then choose and evaluate proportionate controls.|Average all benefits and harms into one positive score.|Consider only people directly using the interface.|The same intervention can distribute value and burden differently, including to non-users.
096|Make claims traceable to evidence, alternatives, uncertainty, and a revisable recommendation.|Present only the final design and its advantages.|Treat confidence of presentation as evidence strength.|A defensible case can withstand scrutiny because its reasoning and limits are visible.
097|Let evidence change framing, alternatives, and commitments throughout the process.|Complete prescribed workshops without changing decisions.|Treat user involvement as validation of an already fixed plan.|Human-centred practice is demonstrated by decisions responding to evidence, not ritual participation.
098|Compare digital intervention with policy or human-service repair, including excluded people and shifted costs.|Digitise the current process before questioning its purpose.|Judge the business case only by reduced digital transaction cost.|A narrow efficiency measure can hide burden and make the wrong intervention appear valuable.
099|Pair colour with text or shape and programmatically available status.|Use red and green with stronger contrast as the sole distinction.|Provide a colour legend instead of a non-colour status cue.|Contrast alone does not make colour-only meaning accessible.
100|Use informative headings and prioritised summaries while retaining consequential detail.|Shorten everything until each section fits a single glance.|Give every paragraph identical emphasis.|Scanning supports orientation; careful reading still needs complete, clearly structured information.
101|Remove avoidable interface burden while preserving necessary decision complexity.|Hide difficult trade-offs to make the flow feel simple.|Treat all cognitive effort as a design failure.|Some effort is inherent in an informed decision. Design should support it rather than disguise it.
102|Restore saved work, orientation, and any changes to the underlying state.|Return the person to the exact old screen without checking freshness.|Restart the flow to avoid stale data.|Resumption requires both continuity and awareness of what changed while the person was away.
103|Offer discoverable guidance and efficient paths as expertise varies by task.|Assign permanent beginner and expert modes to people.|Remove explanations once someone has used the product once.|Expertise is contextual and develops unevenly; support should remain available without imposing unnecessary friction.
104|Consider target size, distance, spacing, and movement while also checking accuracy and consequence.|Optimise speed from target size alone.|Place destructive actions closest to the pointer to minimise movement.|Motor-performance estimates are useful but do not define overall usability or safety.
105|Show evidence of the real state and offer effective control and recovery.|Use reassuring language even when the state is unknown.|Hide the failure once the person dismisses the alert.|Confidence is justified by truthful information and workable action, not tone alone.
106|Explain known progress, uncertain timing, whether leaving is safe, and how completion is communicated.|Use a spinner for every wait, including a multi-day process.|Show a precise countdown unsupported by the service.|Waiting patterns must match timescale and what is actually known.
107|Include exceptions, handoffs, recovery, and differing beliefs about the state.|Model only the most common successful sequence.|Treat every exception as a separate support problem.|The workflow people experience includes breakdown and coordination, not just a happy path.
108|Use scenarios for context, stories for intended value, use cases for interaction paths, and specifications for precise requirements.|Treat these artefacts as interchangeable formats.|Use a user story as a complete account of every exception.|Each representation serves a different reasoning need and should remain traceable to the others.
109|Consider user, data, content, quality, and constraint requirements together and resolve conflicts explicitly.|Prioritise user-facing requirements and defer all constraints.|Treat a list of features as the complete requirement set.|Requirements interact; satisfying one can undermine another unless conflicts are made explicit.
110|Use principles and heuristics to reason, guidelines to specify, and patterns only when their assumptions fit.|Apply familiar patterns without testing the new context.|Treat every heuristic as a mandatory implementation rule.|These tools vary in abstraction and authority. Context determines their appropriate use.
111|Specify decisions, people, methods, logistics, ethics, analysis, owners, and timing.|Write only a discussion guide.|Schedule research after the decision deadline.|An executable plan connects practical delivery to the decision it is meant to inform.
112|Investigate staff work, incentives, policy, capacity, and customer evidence together.|Assume every customer-facing failure is caused by the interface.|Interview customers and infer all operational causes from their accounts.|Customers experience consequences but may not see the mechanisms producing them.
113|Use competitor interfaces as evidence of visible choices, not proof of effectiveness or backstage capability.|Copy a competitor because market presence proves usability.|Infer operating cost from the number of screens.|Competitive review reveals observable design decisions while leaving outcomes and operations uncertain.
114|Ask for sequence, concrete actions, context, and consequences using neutral probes.|Ask whether the proposed feature would have helped.|Suggest a cause and ask the participant to confirm it.|Neutral episode reconstruction reduces the influence of the researcher’s preferred explanation.
115|Observe real work and investigate adaptations with minimal disruption and appropriate consent.|Interrupt each workaround to demonstrate the intended process.|Assume reported practice captures everything that happens.|Observation can expose tacit work, but participant welfare and important activity take priority.
116|Use longitudinal methods for change over time and account for missing entries and research effects.|Treat every missing diary entry as evidence that nothing happened.|Use a single retrospective interview to establish detailed daily change.|Longitudinal evidence has sampling and reactivity limits that must shape interpretation.
117|Check what was measured, who answered, wording effects, and the gap between intention and behaviour.|Treat strong stated preference as a usage forecast.|Increase sample size to eliminate a biased question.|More responses do not repair a poor construct or unrepresentative sample.
118|Treat abandonment as a pattern requiring contextual investigation of possible causes.|Infer that the last screen caused every exit.|Assume all exits represent failure.|An event pattern describes what was recorded, not why it occurred or what happened elsewhere.
119|Share evidence and constraints early so disciplines can change the framing and alternatives.|Ask engineering to estimate only after the solution is fixed.|Use a trio meeting as a substitute for customer evidence.|Cross-functional discovery matters when it changes decisions, not merely attendance.
120|Trace outcomes through opportunities, solutions, and assumptions while checking real-world dependencies.|Treat the tree as proof of a simple causal chain.|Put the preferred feature at the root and work backward.|The tree supports explicit reasoning but cannot remove complexity or validate assumptions by itself.
121|Maintain a rhythm that revisits evidence and decisions, including when no new study is needed.|Run interviews every week regardless of the decision.|Treat discovery cadence as a quota for participant sessions.|A cadence sustains learning; gathering more data is not always the useful next move.
122|Support recruitment, consent, data stewardship, access, and reuse while preserving contextual research judgement.|Standardise every study into the same method.|Treat ResearchOps as scheduling alone.|Operations makes responsible research possible without replacing methodological judgement.
123|Connect themes to specific episodes, context, and contradictory cases.|Choose themes by sticky-note count alone.|Discard negative cases to keep the synthesis coherent.|Traceability and contradiction testing strengthen a theme’s explanatory value.
124|Compare definitions, samples, timing, and what each source can observe.|Choose the source with the largest number of records.|Average conflicting claims without checking their meaning.|Disagreement may reflect different scopes rather than a single source being wrong.
125|State the pattern a story illustrates and the limits of its representativeness.|Let a memorable story stand for the whole population.|Remove the context to make the story seem universal.|A story can illuminate a mechanism without establishing its prevalence.
126|Adapt format and emphasis while keeping the claim, evidence, and confidence consistent.|Strengthen the claim for an executive audience.|Hide uncertainty in short presentations.|Communication can be tailored without changing what the evidence supports.
127|Identify content, ownership, authority, duplication, currency, and unsupported promises.|Count pages and begin redesigning navigation.|Preserve every existing page because it has a URL.|An inventory informs decisions about what should exist and who maintains it, not just where it sits.
128|Model reusable facts through types, attributes, and relationships with clear ownership.|Copy the same fact onto every relevant page.|Use page templates as the only content model.|Structured content reduces conflicting copies and supports reuse across channels.
129|Choose a scheme that fits how the audience seeks information and examine ambiguous boundaries.|Organise by the company’s departments by default.|Use alphabetical ordering for every collection.|Organisation schemes support different seeking behaviours and have distinct trade-offs.
130|Map everyday synonyms to controlled terms while preserving important distinctions.|Require people to know the internal term.|Merge all similar words even when their meanings differ.|Vocabulary control connects language without erasing distinctions needed for accurate retrieval.
131|Provide orientation, related paths, and a way to move through the information space.|Assume the home page establishes enough context.|Show every possible destination at equal prominence.|Navigation supports location and next action without overwhelming the current task.
132|Make relevance and filters understandable and provide useful recovery when no result matches.|Return an empty page when the query fails.|Silently broaden results without explaining the change.|Search recovery should help refine intent while preserving trust in what is shown.
133|Distinguish descriptive attributes, category systems, explicit relationships, and user-created tags.|Treat metadata and taxonomy as synonyms.|Assume informal tags define authoritative relationships.|These structures support different kinds of organisation and inference.
134|Make the destination and its relevance predictable through link text and nearby context.|Use identical “Learn more” labels for unrelated destinations.|Maximise curiosity by hiding what the link contains.|Information scent reduces uncertainty before navigation.
135|Use sitemaps for structural relationships and wireflows for interaction paths and states.|Use isolated polished screens to represent every relationship.|Assume a sitemap captures task recovery behaviour.|Different models expose different dependencies and omissions.
136|Assign ownership, standards, review, migration, and change processes to the structure.|Treat information architecture as finished at launch.|Let each team add categories independently.|An information structure needs governance to remain coherent as content and organisations change.
137|Connect content to user needs, service states, channels, and maintenance responsibility.|Treat each message as an isolated writing task.|Use brand voice as the complete content strategy.|Coherence requires operational and structural decisions as well as style.
138|Use familiar language and a structure that makes the intended action understandable.|Replace long technical words with shorter unexplained abbreviations.|Measure clarity only by sentence length.|Plain language is about comprehension and action, not superficial brevity.
139|Keep the voice recognisable but prioritise clarity, consequence, and recovery in stressful moments.|Use the same playful tone in every situation.|Remove practical information to make the message warmer.|Tone should serve the person’s circumstances rather than perform brand personality.
140|Preserve meaningful order, labels, relationships, and actions across reading modes.|Rely on visual placement to communicate sequence.|Put essential meaning only in an image.|Content must remain understandable when its sensory presentation or reading order changes.
141|Observe how wording changes predictions and actions around consequence and reversibility.|Ask which word sounds nicer.|Choose the shorter label without testing its meaning.|Content testing should examine understanding and behaviour, not preference alone.
142|Trace policy to affected content, owners, channels, publication, and verification.|Update the main page and assume other channels follow.|Leave old messages until users report contradictions.|Governance needs a full change path and checks that the published service is consistent.
143|Use one authoritative state meaning adapted appropriately across channels.|Let each channel invent a more reassuring version.|Assume an email confirmation overrides an unresolved service state.|Channel-specific wording must not create contradictory facts.
144|Check the pattern’s assumptions about task, state, control, and consequences.|Copy the familiar pattern because users recognise it.|Judge fit solely by visual similarity.|Familiarity helps only when the underlying behaviour matches expectations.
145|Choose the medium around environment, precision, privacy, and available abilities.|Use touch whenever a screen is available.|Assume voice is always the accessible alternative.|Every medium creates demands and constraints that must fit the situation.
146|Keep shortcuts discoverable, consistent with visible commands, and protected against costly mistakes.|Hide all visible commands once shortcuts exist.|Optimise keystroke count without considering errors.|Expert efficiency still needs learning support and safe action semantics.
147|Make selection scope, changes, and consequences explicit before bulk commitment.|Assume selection remains valid while the underlying list changes.|Apply an action to hidden items without showing the scope.|Bulk actions amplify ambiguity, so scope and freshness need explicit control.
148|Preserve work and clarify save state, preview, conflicts, and recovery.|Treat successful initial entry as the complete creation journey.|Overwrite conflicting changes to keep the flow simple.|Creation includes persistence and revision, not just entering content.
149|Explain likely consequences before commitment and actual state after action.|Use feedback after the fact as a substitute for informed choice.|Show success before the system confirms it.|Feedforward supports choosing; feedback supports interpreting what actually happened.
150|Introduce guidance when the person has a relevant goal and can use it.|Explain every feature before the first task.|Remove help after onboarding.|Learning is contextual and progressive; front-loading everything creates memory burden.
151|Show definitions, baselines, scale, uncertainty, and relevant comparison.|Use a dramatic slope as sufficient evidence of significance.|Omit uncertainty to make the chart easier to read.|A trend needs context before it can justify a decision.
152|Expose who is acting, shared state, conflicts, and how individual work is protected.|Resolve all conflicts by silently keeping the newest change.|Show collaborators’ avatars without explaining shared-state behaviour.|Collaboration needs understandable coordination rules, not merely presence indicators.
153|Research the needs and workflows of teams building and maintaining products.|Treat designers as the system’s only users.|Measure demand by the number of components requested.|A system serves multiple disciplines and should solve recurring work problems.
154|Keep semantic tokens, specifications, content, behaviour, and code aligned.|Consider matching screenshots sufficient alignment.|Allow design and code to use different state definitions.|A shared visual surface is not enough when meanings or behaviours diverge.
155|Provide contribution and migration paths with owned, reviewable exceptions.|Ban every local exception indefinitely.|Let every team fork without coordination.|Governance must balance coherence with genuine contextual needs and change costs.
156|Test accessibility in component states and real integrations, with regression ownership.|Assume an accessible default screenshot guarantees accessible use.|Delegate every accessibility obligation to consuming teams.|Reusable defects scale quickly. Quality needs evidence at both component and product levels.
157|Map actors, power, value, and dependencies, including affected non-users.|Map only customers who sign in.|Treat every stakeholder as having equal influence.|Ecosystem mapping reveals relationships and asymmetries beyond the interface audience.
158|Follow the delay through people, queues, policy, systems, and capacity.|Start by redesigning the waiting screen.|Ask only patients to identify operational bottlenecks.|Experience evidence must be connected to the operational mechanisms causing the delay.
159|Match interface commitments to actual policy and delivery capacity.|Promise the ideal experience and ask operations to catch up.|Treat capacity as separate from design quality.|An attractive promise that cannot be fulfilled is a service failure.
160|Segment outcomes and measure unfinished needs, staff effort, and displaced waiting.|Celebrate a lower average wait without examining who remains.|Measure only time inside the digital channel.|Averages can conceal exclusion or transfer work to people and channels outside the metric.
161|Examine who benefits, who absorbs burden, and whether alternatives and recourse work.|Use aggregate efficiency as the definition of equity.|Assume equal steps impose equal effort on everyone.|Equal treatment can create unequal consequences under different circumstances.
162|Keep distinct alternatives alive until relevant evidence supports convergence.|Choose the first workable idea to avoid wasted exploration.|Generate alternatives after the decision only for presentation.|Divergence is useful when alternatives can genuinely influence the decision.
163|Use concrete sketches of the same situation to expose different assumptions.|Treat agreement on words as agreement on behaviour.|Polish one sketch before discussing alternatives.|Representing the same scenario makes hidden differences easier to inspect.
164|Make time, data changes, or staff judgement realistic where they determine the learning question.|Choose fidelity only by visual detail.|Simulate every dependency as instant success.|The important realism is the behaviour that can invalidate the proposal.
165|Frame critique around intent, evidence, constraints, and the decision to improve.|Collect personal preferences and average them.|Treat seniority as the deciding evidence.|Useful critique examines reasoning and consequences rather than taste or hierarchy.
166|Combine methods according to risk, stage, people, and conditions.|Use one standard usability test for every question.|Choose the cheapest method regardless of what it can establish.|Evaluation strategy matches evidence to uncertainty, including method limitations.
167|Use moderation when understanding, safety, or adaptation requires careful human support.|Start unmoderated whenever it is cheaper.|Assume remote research removes participant-welfare concerns.|Method choice must consider the learning need and the participant’s experience.
168|Use predictive models for bounded aspects of skilled performance, alongside broader evidence.|Use a motor-time estimate to judge the whole experience.|Assume modelled speed establishes satisfaction.|These models have scope limits and cannot replace evidence about understanding, context, and consequence.
169|Prioritise by consequence, confidence, dependencies, and cost, documenting the trade-offs.|Fix the most frequently mentioned issue first in every case.|Rank findings only by implementation effort.|Frequency and effort alone can miss rare but severe failures or enabling dependencies.
170|Separate work invested, things delivered, user outcomes, and unacceptable side effects.|Treat shipped features as the user outcome.|Assign every team the same target without examining their influence.|Metric roles differ, and teams affect different parts of the causal chain.
171|Use a durable value direction and a stage-specific focus while retaining guardrails.|Allow a single metric to override all safety and quality concerns.|Treat the two metric concepts as identical.|Focus metrics support prioritisation but must not erase other consequential outcomes.
172|Use funnels for sequence, cohorts for comparable groups, and retention for return over time.|Treat conversion as proof of long-term value.|Compare cohorts with different exposure windows without adjustment.|Each view answers a different behavioural question and needs a consistent definition.
173|Investigate clinic capacity or other factors that could affect both data freshness and acceptance.|Conclude that freshness caused acceptance from the correlation.|Dismiss all observational evidence as useless.|Confounding can create an association without the proposed causal effect.
174|Choose assignment and analysis that account for staff or clinic-level spillovers.|Randomise patients independently while assuming staff behaviour cannot cross groups.|Analyse every event as an independent participant.|Interference and clustering can invalidate a naive experiment design.
175|Define a meaningful effect, sensitivity, and decision rule before examining results.|Stop when a favourable p-value appears.|Choose the practical threshold after seeing the estimated effect.|Predefined criteria reduce opportunistic interpretation and connect statistics to decisions.
176|Define events and state transitions consistently across systems, preserving reservation versus acceptance.|Merge similar-looking events to simplify the dashboard.|Treat successful logging as proof of meaningful measurement.|Reliable measurement requires semantic consistency as well as technical delivery.
177|Build valid experiments, preserve learning, and change decisions when evidence warrants it.|Reward the number of tests run regardless of validity.|Publish only winning experiments.|Experimentation maturity concerns reliable learning and its use, not test volume.
178|Trace accumulated effort, dependencies, and exclusions across the whole journey.|Approve each usable screen and infer the journey is inclusive.|Measure only the single hardest step.|Several individually manageable demands can combine into an inaccessible journey.
179|Learn from edge experiences and give participants real influence over alternatives and decisions.|Invite participation after the solution is fixed.|Treat one participant as representative of every excluded group.|Participation is meaningful when it can change the design, with appropriate limits on representation.
180|Choose and combine approaches based on their aims, participation, and context rather than treating them as synonyms.|Use universal design to claim every need is solved.|Assume user-centred work always includes shared decision power.|The approaches overlap but differ in ambition, methods, and how power is shared.
181|Combine scoped automated, manual, and assistive-technology evaluation with documented evidence.|Claim conformance from a clean automated scan.|Treat one successful user session as proof of complete conformance.|Automation covers only part of accessibility; claims require a defined scope and appropriate checks.
182|Assign ownership, regression checks, reporting, and repair throughout change.|Treat an accessibility review as a permanent certification.|Wait for complaints before considering regressions.|Accessibility is maintained through ongoing product and organisational practices.
183|Justify the field’s purpose and proportionality, consider alternatives, and govern its lifecycle.|Collect it because another product does.|Make it optional and ignore retention and later use.|Optional collection can still create risk. Necessity and handling need a defensible purpose.
184|Compare actual burdens, outcomes, power, and available recourse across groups.|Assume one rule guarantees fairness.|Judge equity only by equal interface access.|Identical rules can interact differently with people’s resources and circumstances.
185|Provide authority, protected reporting, named ownership, and a route to pause or change the decision.|Ask the researcher to raise concerns without giving anyone response responsibility.|Treat the fixed date as overriding evidence of harm.|Escalation needs practical power and accountability, not an invitation to speak without consequence.
186|Show human and AI roles, uncertainty, authority, failures, and handoffs.|Storyboard only the successful generated output.|Treat the human role as approving whatever the model produces.|The experience is a joint system whose failure and control paths need design.
187|Trace changes to decisions, incentives, data, and feedback loops beyond the interface.|Treat AI as a drop-in replacement with no workflow effects.|Evaluate only the presentation of the generated answer.|AI can alter the system that generates future inputs and decisions.
188|Use a metaphor that matches actual capability, authority, and accountability.|Call the system a teammate while implying unsupported independent judgement.|Choose the most engaging character regardless of expectations.|Metaphors shape reliance and should not overstate what the system can responsibly do.
189|Check whether sources support the claim and are current, applicable, and consistent, with recourse for failure.|Trust an answer because its citations exist.|Assume more citations necessarily mean stronger evidence.|Citation presence does not establish relevance, validity, or safe application.
190|Choose intervention thresholds using consequences, uncertainty, and review capacity.|Apply the highest-probability label directly as the action.|Use one threshold for every kind of harm.|A prediction and a decision policy are different; consequences determine how evidence should trigger action.
191|Include operators, recipients, affected non-users, and people bearing downstream consequences.|Research only people using the AI interface.|Use the model team as a substitute for affected people.|The impact boundary is wider than the direct-user boundary.
192|Trace generated themes to authorised evidence, inspect omissions and negative cases, and retain human accountability.|Accept fluent synthesis as a validated finding.|Use AI output to replace checking the underlying notes.|AI can assist synthesis but does not establish evidential validity or transfer responsibility.
193|Use rapid iterative testing for observable usability issues while using other methods for broader claims.|Use RITE to establish long-term causal impact.|Treat every change between sessions as scientifically comparable evidence.|Fast iteration is useful within its scope, not a substitute for every evaluation design.
194|Connect model claims to operational controls, ownership, monitoring, and evidence of effectiveness.|Declare trustworthiness from a model benchmark.|Publish principles without testing their implementation.|Trustworthiness depends on the deployed socio-technical system and its actual controls.
195|Investigate whether reviewers independently detect errors and can meaningfully disagree.|Treat rising agreement as proof of model improvement.|Count approvals as evidence that human oversight is effective.|Agreement can reflect automation bias or lost review capacity rather than correctness.
196|Clarify who decides, who contributes expertise, and who remains accountable.|Give decision authority automatically to the loudest expert.|Treat consultation as equivalent to shared decision authority.|Roles must be explicit so contribution, expertise, and responsibility are not confused.
197|Make assumptions revisable and define how new evidence can change scope or commitment.|Freeze the learning agenda once estimates are agreed.|Record evidence without allowing it to affect delivery.|Learning inside delivery needs an actual mechanism for changing the work.
198|Build the smallest credible test of value while preserving essential safety, consent, and recovery.|Remove safeguards to make the product minimal.|Ship a small feature without defining what it tests.|Minimum scope should reduce investment, not invalidate learning or transfer unacceptable risk.
199|Test problem validity, solution usability, and eventual outcomes as separate claims.|Treat a usable prototype as proof that the problem is worth solving.|Use expressed demand as evidence that the interaction works.|Evidence for one layer does not automatically validate the others.
200|Plan detection, affected-person identification, pause, rollback or repair, and safe resumption.|Treat deployment success as the end of the rollout.|Pause the feature without helping people already affected.|Responsible rollout includes recovery for real people and evidence for restarting.
201|Connect substitution expectations to availability, fulfilment incentives, and workable recovery.|Optimise checkout while leaving substitution decisions unexplained.|Treat a successful payment as the completed grocery outcome.|The service promise reaches fulfilment; uncertainty before purchase changes the whole journey.
202|Support expert comparison, roles, state, and exception handling without hiding necessary detail.|Remove dense information solely to make the screen look cleaner.|Assume fewer visible controls always improve enterprise usability.|Expert work can require density; clarity comes from structure and relevance rather than indiscriminate removal.
203|Align state, ownership, policy, capacity, and recovery across digital and assisted channels.|Treat phone and digital changes as independent services.|Confirm a change before its operational dependencies agree.|A coherent service maintains one truthful outcome across its channels and handoffs.
204|Evaluate correct and equitable outcomes, authoritative evidence, alternatives, appeal, and remedy.|Use completion as the main proof of safety.|Treat a polished interface and an explanation as sufficient accountability.|High-stakes services require reliable decisions and meaningful recourse, not just task completion.
`;

export const quizzes=Object.fromEntries(rows.trim().split('\n').map(line=>{
  const [number,correct,wrong1,wrong2,explanation]=line.split('|');
  const offset=Number(number)%3;
  const options=[correct,wrong1,wrong2];
  const ordered=options.slice(offset).concat(options.slice(0,offset));
  const id='UX-'+number;
  return [id,{prompt:recallPrompts[id]+' Choose the strongest response.',options:ordered,correct:ordered.indexOf(correct),explanation}];
}));
for(const [id,q] of Object.entries(quizzes)){
  if(!q.prompt||q.options.length!==3||q.options.some(x=>!x)||!q.explanation||new Set(q.options).size!==3)throw new Error('Invalid quiz: '+id);
}
if(Object.keys(quizzes).length!==204)throw new Error('Expected 204 authored quizzes');
